#include "Presets/PresetAuthoring.h"
#include "Presets/Banks.h"

/*
    RIPPLES — the DEEP BLUE bank.

    See Presets/PresetAuthoring.h for the unit helpers and the make() form, and
    docs/PRESET_GUIDE.md for what makes a preset in this bank good.
*/

namespace ripples::factory
{

//==============================================================================
//  DEEP BLUE — open water. Wide, slow, blue. The centre of the product.
//==============================================================================
void addDeepBlueBank (std::vector<Preset>& out)
{
    // The default preset. One chord has to say what RIPPLES is: deep, moving,
    // wide, unmistakably underwater, and still musical enough to keep.
    out.push_back (make (kDeepBlue, "SUBMERGED DREAMS", "Pad", { "Deep", "Cinematic" }, Dry::No,
        "The first thing you hear. A five-voice Water pad over a Hollow layer, "
        "sunk under an LP24 at 900 Hz with the pressure control filling the low "
        "mids. Drift detunes it a few cents over half a minute, Current walks "
        "the A/B balance, slow droplets fall somewhere behind it, and the whole "
        "thing sits in a wide, dark, modulated Abyss reverb.",
    {
        { pid::oscAWave,      wv (OscWave::Water) },
        { pid::oscAShape,     0.42f },
        { pid::oscAUnison,    uni (5) },
        { pid::oscADetune,    0.22f },
        { pid::oscAStereo,    0.90f },
        { pid::oscAPan,       bip (-0.08f) },
        { pid::oscALevel,     lvl (-4.0f) },

        { pid::oscBWave,      wv (OscWave::Hollow) },
        { pid::oscBShape,     0.55f },
        { pid::oscBOctave,    oct (0) },
        { pid::oscBFine,      cents (-7.0f) },
        { pid::oscBUnison,    uni (3) },
        { pid::oscBDetune,    0.18f },
        { pid::oscBStereo,    0.85f },
        { pid::oscBPan,       bip (0.08f) },
        { pid::oscBLevel,     lvl (-7.0f) },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subOctave,     subOct (-1) },
        { pid::subLevel,      lvl (-23.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-30.0f) },
        { pid::noiseTone,     0.35f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (3200.0f) },
        { pid::filtReso,      0.28f },
        { pid::filtDrive,     0.18f },
        { pid::filtKeyTrack,  0.35f },
        { pid::filtEnvAmt,    bip (0.30f) },
        { pid::filtMovement,  0.50f },
        { pid::filtPressure,  0.45f },

        { pid::fenvAttack,    att (1.20f) },
        { pid::fenvDecay,     dec (3.00f) },
        { pid::fenvSustain,   0.55f },
        { pid::fenvRelease,   rel (4.00f) },
        { pid::fenvVelocity,  0.35f },

        { pid::aenvAttack,    att (0.90f) },
        { pid::aenvDecay,     dec (2.50f) },
        { pid::aenvSustain,   0.85f },
        { pid::aenvRelease,   rel (4.50f) },
        { pid::aenvVelocity,  0.35f },

        { pid::macroDepth,    0.70f },
        { pid::macroWet,      0.55f },
        { pid::macroRipple,   0.25f },
        { pid::macroCurrent,  0.45f },
        { pid::macroDrops,    0.25f },
        { pid::macroPressure, 0.45f },
        { pid::macroSpace,    0.70f },
        { pid::macroGlow,     0.40f },
        { pid::fluidX,        bip (-0.35f) },
        { pid::fluidY,        bip (0.55f) },
        { pid::fluidXAmount,  0.55f },
        { pid::fluidYAmount,  0.75f },

        { pid::tideShape,     ts (TideShape::Flow) },
        { pid::tideRate,      tideHz (0.16f) },
        { pid::tideDepth,     0.42f },
        { pid::tideStereo,    0.65f },
        { pid::currRate,      currHz (0.22f) },
        { pid::currAmount,    0.50f },
        { pid::currSmooth,    0.75f },
        { pid::currDrift,     0.35f },
        { pid::currStereo,    0.80f },
        { pid::driftRate,     driftHz (0.02f) },
        { pid::driftAmount,   0.50f },
        { pid::driftStereo,   0.90f },
        { pid::rippleRate,    rippleHz (2.2f) },
        { pid::rippleDecay,   0.75f },
        { pid::rippleDepth,   0.22f },
        { pid::rippleCycles,  cycles (3.0f) },
        { pid::rippleSpread,  0.60f },

        { pid::dropAmount,    0.22f },
        { pid::dropDensity,   0.18f },
        { pid::dropSize,      0.62f },
        { pid::dropTone,      0.42f },
        { pid::dropSplash,    0.30f },
        { pid::dropGravity,   0.55f },
        { pid::dropBounce,    0.25f },
        { pid::dropRandom,    0.70f },
        { pid::dropSpread,    0.90f },

        { pid::resoAmount,    0.34f },
        { pid::resoSize,      0.68f },
        { pid::resoDecay,     0.62f },
        { pid::resoDamping,   0.55f },
        { pid::resoScatter,   0.35f },
        { pid::resoMotion,    0.35f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.40f },
        { pid::scurRate,      scurHz (0.06f) },
        { pid::scurWidth,     0.60f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.18f) },
        { pid::chorDepth,     0.50f },
        { pid::chorDelay,     chdel (22.0f) },
        { pid::chorFeedback,  0.20f },
        { pid::chorWidth,     0.70f },
        { pid::chorMix,       0.35f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (0.55f) },
        { pid::dlyFeedback,   0.42f },
        { pid::dlyMotion,     0.45f },
        { pid::dlySpread,     0.50f },
        { pid::dlyDamping,    0.68f },
        { pid::dlyDiffusion,  0.45f },
        { pid::dlyMix,        0.26f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.55f },
        { pid::diffSize,      0.60f },
        { pid::diffDamping,   0.50f },
        { pid::diffMix,       0.32f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.80f },
        { pid::verbDecay,     0.78f },
        { pid::verbPredelay,  pre (45.0f) },
        { pid::verbDamping,   0.55f },
        { pid::verbLowCut,    vLowHz (90.0f) },
        { pid::verbHighCut,   vHighHz (6500.0f) },
        { pid::verbMod,       0.45f },
        { pid::verbMix,       0.45f },

        { pid::mastLow,       eqdb (1.0f) },
        { pid::mastMid,       eqdb (-1.0f) },
        { pid::mastHigh,      eqdb (-0.5f) },
        { pid::mastDrive,     0.12f },
        { pid::mastCeiling,   ceildb (-0.5f) },
    },
    {
        { ModSource::Drift,       ModDest::FineAll,         0.18f },
        { ModSource::Drift,       ModDest::FilterCutoff,    0.25f },
        { ModSource::Current,     ModDest::OscMix,          0.35f },
        { ModSource::Current,     ModDest::FilterCutoff,    0.30f },
        { ModSource::Tide,        ModDest::ShapeA,          0.35f },
        { ModSource::Tide,        ModDest::ResonatorSize,   0.20f },
        { ModSource::ModEnvelope, ModDest::FilterMovement,  0.30f },
        { ModSource::Velocity,    ModDest::FilterCutoff,    0.28f },
        { ModSource::ModWheel,    ModDest::ReverbMix,       0.35f },
        { ModSource::Ripple,      ModDest::PitchAll,        0.05f },
        { ModSource::KeyTrack,    ModDest::Amplitude,      -0.12f },
        { ModSource::Aftertouch,  ModDest::DropletAmount,   0.40f },
    }));

    // --- DRY AQUATIC #6 ----------------------------------------------------
    out.push_back (make (kDeepBlue, "SUBMERGED", "Pad", { "Submerged", "Deep", "Wet" }, Dry::Yes,
        "The proof that the reverb is optional. Six-voice Water spread hard "
        "across the field, Deep noise breathing under the Tide, and a large slow "
        "resonator standing in for the room. The LP24 is written high enough "
        "that DEPTH at 0.80 still leaves it open around a kilohertz, so the "
        "patch is submerged rather than smothered.",
    {
        RIPPLES_FX_BYPASSED,

        { pid::oscAWave,      wv (OscWave::Water) },
        { pid::oscAShape,     0.35f },
        { pid::oscAUnison,    uni (6) },
        { pid::oscADetune,    0.26f },
        { pid::oscAStereo,    0.95f },
        { pid::oscALevel,     lvl (-3.5f) },

        { pid::oscBWave,      wv (OscWave::Hollow) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBFine,      cents (-11.0f) },
        { pid::oscBUnison,    uni (4) },
        { pid::oscBDetune,    0.22f },
        { pid::oscBStereo,    0.90f },
        { pid::oscBLevel,     lvl (-8.0f) },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subLevel,      lvl (-19.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-21.0f) },
        { pid::noiseTone,     0.22f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (3400.0f) },
        { pid::filtReso,      0.34f },
        { pid::filtDrive,     0.24f },
        { pid::filtKeyTrack,  0.30f },
        { pid::filtEnvAmt,    bip (0.38f) },
        { pid::filtPressure,  0.70f },

        { pid::fenvAttack,    att (1.80f) },
        { pid::fenvDecay,     dec (5.00f) },
        { pid::fenvSustain,   0.50f },
        { pid::fenvRelease,   rel (6.00f) },
        { pid::fenvVelocity,  0.30f },

        { pid::aenvAttack,    att (1.40f) },
        { pid::aenvDecay,     dec (4.00f) },
        { pid::aenvSustain,   0.88f },
        { pid::aenvRelease,   rel (6.50f) },
        { pid::aenvVelocity,  0.30f },

        { pid::macroDepth,    0.80f },
        { pid::macroWet,      0.70f },
        { pid::macroCurrent,  0.55f },
        { pid::macroPressure, 0.70f },
        { pid::macroDrops,    0.30f },
        { pid::macroGlow,     0.20f },
        { pid::fluidX,        bip (-0.45f) },
        { pid::fluidY,        bip (0.80f) },
        { pid::fluidYAmount,  0.85f },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.09f) },
        { pid::tideDepth,     0.60f },
        { pid::tideStereo,    0.70f },
        { pid::currRate,      currHz (0.16f) },
        { pid::currAmount,    0.62f },
        { pid::currSmooth,    0.85f },
        { pid::currDrift,     0.45f },
        { pid::currStereo,    0.90f },
        { pid::driftRate,     driftHz (0.015f) },
        { pid::driftAmount,   0.60f },
        { pid::driftStereo,   0.95f },
        { pid::rippleRate,    rippleHz (1.4f) },
        { pid::rippleDecay,   0.85f },
        { pid::rippleDepth,   0.30f },
        { pid::rippleCycles,  cycles (2.0f) },

        { pid::dropAmount,    0.26f },
        { pid::dropDensity,   0.14f },
        { pid::dropSize,      0.78f },
        { pid::dropTone,      0.24f },
        { pid::dropSplash,    0.20f },
        { pid::dropGravity,   0.45f },
        { pid::dropBounce,    0.15f },
        { pid::dropRandom,    0.75f },
        { pid::dropSpread,    0.95f },

        { pid::resoAmount,    0.58f },
        { pid::resoSize,      0.88f },
        { pid::resoDecay,     0.80f },
        { pid::resoDamping,   0.72f },
        { pid::resoScatter,   0.45f },
        { pid::resoMotion,    0.45f },

        { pid::mastLow,       eqdb (2.0f) },
        { pid::mastHigh,      eqdb (-3.0f) },
        { pid::mastDrive,     0.15f },
    },
    {
        { ModSource::Tide,     ModDest::NoiseLevel,      0.45f },
        { ModSource::Tide,     ModDest::FilterCutoff,    0.30f },
        { ModSource::Current,  ModDest::FilterCutoff,    0.35f },
        { ModSource::Current,  ModDest::ResonatorSize,   0.30f },
        { ModSource::Drift,    ModDest::FineAll,         0.25f },
        { ModSource::Drift,    ModDest::ResonatorDamping, 0.30f },
        { ModSource::Ripple,   ModDest::FilterCutoff,    0.20f },
        { ModSource::ModWheel, ModDest::FilterCutoff,    0.40f },
        { ModSource::Velocity, ModDest::FilterCutoff,    0.20f },
        { ModSource::Aftertouch, ModDest::ResonatorAmount, 0.35f },
    }));

    out.push_back (make (kDeepBlue, "BLUE CATHEDRAL", "Pad", { "Cinematic", "Dreamy", "Deep" }, Dry::No,
        "Enormous. A slow choir of Water and Glass an octave apart, a 45-second "
        "reverb tail and a 90 ms pre-delay so the attack is still audible before "
        "the room swallows it. Play three notes and leave them.",
    {
        { pid::oscAWave,      wv (OscWave::Water) },
        { pid::oscAShape,     0.50f },
        { pid::oscAUnison,    uni (7) },
        { pid::oscADetune,    0.30f },
        { pid::oscAStereo,    1.00f },
        { pid::oscALevel,     lvl (-5.0f) },

        { pid::oscBWave,      wv (OscWave::Glass) },
        { pid::oscBOctave,    oct (1) },
        { pid::oscBShape,     0.45f },
        { pid::oscBFine,      cents (5.0f) },
        { pid::oscBUnison,    uni (4) },
        { pid::oscBDetune,    0.26f },
        { pid::oscBStereo,    0.95f },
        { pid::oscBLevel,     lvl (-13.0f) },

        { pid::subLevel,      lvl (-20.0f) },
        { pid::noiseType,     nz (NoiseType::Air) },
        { pid::noiseLevel,    lvl (-28.0f) },
        { pid::noiseTone,     0.55f },

        { pid::filtMode,      fm (FilterMode::LP12) },
        { pid::filtCutoff,    hz (2200.0f) },
        { pid::filtReso,      0.20f },
        { pid::filtDrive,     0.10f },
        { pid::filtKeyTrack,  0.40f },
        { pid::filtEnvAmt,    bip (0.32f) },
        { pid::filtPressure,  0.40f },

        { pid::fenvAttack,    att (3.50f) },
        { pid::fenvDecay,     dec (8.00f) },
        { pid::fenvSustain,   0.65f },
        { pid::fenvRelease,   rel (9.00f) },

        { pid::aenvAttack,    att (2.80f) },
        { pid::aenvDecay,     dec (6.00f) },
        { pid::aenvSustain,   0.90f },
        { pid::aenvRelease,   rel (8.00f) },
        { pid::aenvVelocity,  0.25f },

        { pid::macroDepth,    0.55f },
        { pid::macroWet,      0.60f },
        { pid::macroSpace,    0.95f },
        { pid::macroGlow,     0.55f },
        { pid::macroCurrent,  0.40f },
        { pid::fluidX,        bip (-0.55f) },
        { pid::fluidY,        bip (0.35f) },

        { pid::tideShape,     ts (TideShape::Flow) },
        { pid::tideRate,      tideHz (0.07f) },
        { pid::tideDepth,     0.40f },
        { pid::tideStereo,    0.80f },
        { pid::currRate,      currHz (0.12f) },
        { pid::currAmount,    0.45f },
        { pid::currSmooth,    0.88f },
        { pid::driftRate,     driftHz (0.012f) },
        { pid::driftAmount,   0.55f },
        { pid::driftStereo,   0.95f },

        { pid::resoAmount,    0.28f },
        { pid::resoSize,      0.82f },
        { pid::resoDecay,     0.70f },
        { pid::resoDamping,   0.48f },
        { pid::resoScatter,   0.30f },
        { pid::resoMotion,    0.30f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.45f },
        { pid::scurRate,      scurHz (0.04f) },
        { pid::scurWidth,     0.70f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.12f) },
        { pid::chorDepth,     0.55f },
        { pid::chorDelay,     chdel (28.0f) },
        { pid::chorWidth,     0.80f },
        { pid::chorMix,       0.38f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (1.20f) },
        { pid::dlyFeedback,   0.52f },
        { pid::dlyMotion,     0.50f },
        { pid::dlySpread,     0.70f },
        { pid::dlyDamping,    0.72f },
        { pid::dlyDiffusion,  0.60f },
        { pid::dlyMix,        0.28f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.70f },
        { pid::diffSize,      0.75f },
        { pid::diffMix,       0.40f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.95f },
        { pid::verbDecay,     0.92f },
        { pid::verbPredelay,  pre (90.0f) },
        { pid::verbDamping,   0.45f },
        { pid::verbLowCut,    vLowHz (140.0f) },
        { pid::verbHighCut,   vHighHz (7500.0f) },
        { pid::verbMod,       0.55f },
        { pid::verbMix,       0.58f },

        { pid::mastLow,       eqdb (-1.0f) },
        { pid::mastHigh,      eqdb (1.0f) },
        { pid::mastCeiling,   ceildb (-0.8f) },
    },
    {
        { ModSource::Drift,       ModDest::FineAll,       0.22f },
        { ModSource::Drift,       ModDest::ReverbSize,    0.25f },
        { ModSource::Tide,        ModDest::ShapeA,        0.40f },
        { ModSource::Tide,        ModDest::LevelB,        0.30f },
        { ModSource::Current,     ModDest::FilterCutoff,  0.30f },
        { ModSource::Current,     ModDest::DiffusionAmount, 0.25f },
        { ModSource::ModEnvelope, ModDest::ShapeB,        0.35f },
        { ModSource::ModWheel,    ModDest::ReverbMix,     0.40f },
        { ModSource::Note,        ModDest::FilterCutoff,  0.20f },
    }));

    out.push_back (make (kDeepBlue, "THERMOCLINE", "Pad", { "Deep", "Calm", "Submerged" }, Dry::No,
        "The boundary layer, where warm water meets cold. The Morph filter walks "
        "from low-pass to band-pass under Drift, so the timbre crosses over and "
        "back without you touching anything.",
    {
        { pid::oscAWave,      wv (OscWave::Hollow) },
        { pid::oscAShape,     0.38f },
        { pid::oscAUnison,    uni (4) },
        { pid::oscADetune,    0.20f },
        { pid::oscAStereo,    0.85f },
        { pid::oscALevel,     lvl (-4.0f) },

        { pid::oscBWave,      wv (OscWave::Water) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBShape,     0.60f },
        { pid::oscBFine,      cents (9.0f) },
        { pid::oscBUnison,    uni (3) },
        { pid::oscBDetune,    0.24f },
        { pid::oscBStereo,    0.90f },
        { pid::oscBLevel,     lvl (-6.5f) },
        { pid::oscBInterMode, im (InteractionMode::Crossfade) },
        { pid::oscBInterAmt,  0.45f },

        { pid::subLevel,      lvl (-19.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-27.0f) },
        { pid::noiseTone,     0.30f },

        { pid::filtMode,      fm (FilterMode::Morph) },
        { pid::filtCutoff,    hz (1100.0f) },
        { pid::filtReso,      0.30f },
        { pid::filtDrive,     0.16f },
        { pid::filtKeyTrack,  0.40f },
        { pid::filtEnvAmt,    bip (0.25f) },
        { pid::filtMovement,  0.30f },
        { pid::filtPressure,  0.50f },

        { pid::fenvAttack,    att (2.00f) },
        { pid::fenvDecay,     dec (5.00f) },
        { pid::fenvSustain,   0.55f },
        { pid::fenvRelease,   rel (5.00f) },

        { pid::aenvAttack,    att (1.60f) },
        { pid::aenvDecay,     dec (4.00f) },
        { pid::aenvSustain,   0.85f },
        { pid::aenvRelease,   rel (5.00f) },
        { pid::aenvVelocity,  0.30f },

        { pid::macroDepth,    0.65f },
        { pid::macroWet,      0.50f },
        { pid::macroCurrent,  0.60f },
        { pid::macroPressure, 0.50f },
        { pid::macroSpace,    0.55f },
        { pid::fluidX,        bip (-0.40f) },
        { pid::fluidY,        bip (0.45f) },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.11f) },
        { pid::tideDepth,     0.50f },
        { pid::tideStereo,    0.60f },
        { pid::currRate,      currHz (0.20f) },
        { pid::currAmount,    0.55f },
        { pid::currSmooth,    0.80f },
        { pid::currDrift,     0.50f },
        { pid::driftRate,     driftHz (0.008f) },
        { pid::driftAmount,   0.70f },
        { pid::driftStereo,   0.85f },

        { pid::dropAmount,    0.18f },
        { pid::dropDensity,   0.16f },
        { pid::dropSize,      0.70f },
        { pid::dropTone,      0.35f },
        { pid::dropSpread,    0.85f },

        { pid::resoAmount,    0.36f },
        { pid::resoSize,      0.72f },
        { pid::resoDecay,     0.66f },
        { pid::resoDamping,   0.62f },
        { pid::resoMotion,    0.40f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.40f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.15f) },
        { pid::chorDepth,     0.48f },
        { pid::chorMix,       0.30f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (0.85f) },
        { pid::dlyFeedback,   0.40f },
        { pid::dlyDamping,    0.72f },
        { pid::dlyMix,        0.22f },
        { pid::diffEnable,    on },
        { pid::diffMix,       0.30f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.78f },
        { pid::verbDecay,     0.74f },
        { pid::verbDamping,   0.60f },
        { pid::verbMix,       0.40f },
        { pid::mastLow,       eqdb (1.0f) },
    },
    {
        { ModSource::Drift,       ModDest::FilterMovement,    0.60f },
        { ModSource::Drift,       ModDest::FineAll,           0.20f },
        { ModSource::Current,     ModDest::InteractionAmount, 0.45f },
        { ModSource::Current,     ModDest::FilterCutoff,      0.30f },
        { ModSource::Tide,        ModDest::FilterCutoff,      0.35f },
        { ModSource::Tide,        ModDest::OscMix,            0.25f },
        { ModSource::ModEnvelope, ModDest::ResonatorSize,     0.25f },
        { ModSource::ModWheel,    ModDest::FilterMovement,    0.40f },
    }));

    out.push_back (make (kDeepBlue, "WHALEFALL", "Drone", { "Deep", "Dark", "Cinematic" }, Dry::No,
        "A hold-one-note drone. Sub-heavy, slow, with a long resonator and a "
        "Swell tide that makes the whole thing breathe once every twenty "
        "seconds. Nothing here is fast.",
    {
        { pid::oscAWave,      wv (OscWave::Hollow) },
        { pid::oscAShape,     0.30f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (5) },
        { pid::oscADetune,    0.28f },
        { pid::oscAStereo,    0.90f },
        { pid::oscALevel,     lvl (-5.0f) },

        { pid::oscBWave,      wv (OscWave::Water) },
        { pid::oscBOctave,    oct (-2) },
        { pid::oscBFine,      cents (-14.0f) },
        { pid::oscBUnison,    uni (3) },
        { pid::oscBDetune,    0.30f },
        { pid::oscBLevel,     lvl (-7.0f) },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subOctave,     subOct (-2) },
        { pid::subLevel,      lvl (-9.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-23.0f) },
        { pid::noiseTone,     0.12f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (320.0f) },
        { pid::filtReso,      0.26f },
        { pid::filtDrive,     0.28f },
        { pid::filtKeyTrack,  0.25f },
        { pid::filtEnvAmt,    bip (0.20f) },
        { pid::filtPressure,  0.65f },

        { pid::fenvAttack,    att (5.00f) },
        { pid::fenvDecay,     dec (12.00f) },
        { pid::fenvSustain,   0.70f },
        { pid::fenvRelease,   rel (10.00f) },

        { pid::aenvAttack,    att (4.00f) },
        { pid::aenvDecay,     dec (10.00f) },
        { pid::aenvSustain,   0.95f },
        { pid::aenvRelease,   rel (12.00f) },
        { pid::aenvVelocity,  0.15f },

        { pid::macroDepth,    0.90f },
        { pid::macroPressure, 0.70f },
        { pid::macroWet,      0.45f },
        { pid::macroSpace,    0.75f },
        { pid::macroGlow,     0.10f },
        { pid::fluidX,        bip (-0.60f) },
        { pid::fluidY,        bip (0.85f) },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.05f) },
        { pid::tideDepth,     0.65f },
        { pid::tideStereo,    0.55f },
        { pid::currRate,      currHz (0.09f) },
        { pid::currAmount,    0.50f },
        { pid::currSmooth,    0.90f },
        { pid::driftRate,     driftHz (0.006f) },
        { pid::driftAmount,   0.65f },

        { pid::resoAmount,    0.42f },
        { pid::resoSize,      0.95f },
        { pid::resoDecay,     0.85f },
        { pid::resoDamping,   0.75f },
        { pid::resoScatter,   0.25f },
        { pid::resoMotion,    0.35f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.35f },
        { pid::scurRate,      scurHz (0.03f) },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (1.60f) },
        { pid::dlyFeedback,   0.45f },
        { pid::dlyDamping,    0.85f },
        { pid::dlyMix,        0.20f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.50f },
        { pid::diffMix,       0.26f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.90f },
        { pid::verbDecay,     0.88f },
        { pid::verbDamping,   0.70f },
        { pid::verbLowCut,    vLowHz (60.0f) },
        { pid::verbHighCut,   vHighHz (3500.0f) },
        { pid::verbMix,       0.42f },

        { pid::mastLow,       eqdb (3.0f) },
        { pid::mastHigh,      eqdb (-4.0f) },
        { pid::mastDrive,     0.20f },
        { pid::voiceCount,    vox (4) },
    },
    {
        { ModSource::Tide,     ModDest::Amplitude,       0.30f },
        { ModSource::Tide,     ModDest::FilterCutoff,    0.35f },
        { ModSource::Drift,    ModDest::FineAll,         0.30f },
        { ModSource::Drift,    ModDest::ResonatorDecay,  0.25f },
        { ModSource::Current,  ModDest::NoiseTone,       0.35f },
        { ModSource::Current,  ModDest::PanA,            0.40f },
        { ModSource::ModWheel, ModDest::ResonatorAmount, 0.45f },
    }));

    out.push_back (make (kDeepBlue, "MIDWATER", "Key", { "Deep", "Dreamy", "Wet" }, Dry::No,
        "A soft electric-piano shape for chords in the middle of a track. Fast "
        "attack, long tail, low resonance, nothing sharp anywhere.",
    {
        { pid::oscAWave,      wv (OscWave::Sine) },
        { pid::oscAUnison,    uni (3) },
        { pid::oscADetune,    0.14f },
        { pid::oscAStereo,    0.70f },
        { pid::oscALevel,     lvl (-3.0f) },

        { pid::oscBWave,      wv (OscWave::Water) },
        { pid::oscBOctave,    oct (1) },
        { pid::oscBShape,     0.40f },
        { pid::oscBLevel,     lvl (-12.0f) },
        { pid::oscBInterMode, im (InteractionMode::PhaseMod) },
        { pid::oscBInterAmt,  0.22f },

        { pid::subLevel,      lvl (-16.0f) },
        { pid::noiseType,     nz (NoiseType::Bubble) },
        { pid::noiseLevel,    lvl (-29.0f) },
        { pid::noiseTone,     0.40f },

        { pid::filtMode,      fm (FilterMode::LP12) },
        { pid::filtCutoff,    hz (1900.0f) },
        { pid::filtReso,      0.18f },
        { pid::filtDrive,     0.14f },
        { pid::filtKeyTrack,  0.60f },
        { pid::filtEnvAmt,    bip (0.45f) },
        { pid::filtPressure,  0.40f },

        { pid::fenvAttack,    att (0.004f) },
        { pid::fenvDecay,     dec (1.60f) },
        { pid::fenvSustain,   0.20f },
        { pid::fenvRelease,   rel (1.50f) },
        { pid::fenvVelocity,  0.55f },

        { pid::aenvAttack,    att (0.010f) },
        { pid::aenvDecay,     dec (3.00f) },
        { pid::aenvSustain,   0.45f },
        { pid::aenvRelease,   rel (2.20f) },
        { pid::aenvVelocity,  0.65f },

        { pid::macroDepth,    0.50f },
        { pid::macroWet,      0.50f },
        { pid::macroSpace,    0.55f },
        { pid::macroGlow,     0.35f },
        { pid::fluidX,        bip (-0.30f) },
        { pid::fluidY,        bip (0.30f) },

        { pid::tideRate,      tideHz (0.30f) },
        { pid::tideDepth,     0.25f },
        { pid::tideStereo,    0.55f },
        { pid::currRate,      currHz (0.35f) },
        { pid::currAmount,    0.40f },
        { pid::currSmooth,    0.75f },
        { pid::driftRate,     driftHz (0.03f) },
        { pid::driftAmount,   0.35f },

        { pid::dropAmount,    0.16f },
        { pid::dropDensity,   0.20f },
        { pid::dropSize,      0.55f },
        { pid::dropTone,      0.50f },

        { pid::resoAmount,    0.26f },
        { pid::resoSize,      0.60f },
        { pid::resoDecay,     0.52f },
        { pid::resoDamping,   0.58f },

        { pid::scurEnable,    on },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.30f) },
        { pid::chorDepth,     0.42f },
        { pid::chorMix,       0.30f },
        { pid::dlyEnable,     on },
        { pid::dlySync,       on },
        { pid::dlySyncTime,   sd (SyncDivision::QuarterD) },
        { pid::dlyFeedback,   0.35f },
        { pid::dlyDamping,    0.72f },
        { pid::dlyMix,        0.22f },
        { pid::diffEnable,    on },
        { pid::diffMix,       0.26f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.68f },
        { pid::verbDecay,     0.66f },
        { pid::verbMix,       0.38f },
    },
    {
        { ModSource::Velocity,    ModDest::FilterCutoff,      0.45f },
        { ModSource::Velocity,    ModDest::InteractionAmount, 0.30f },
        { ModSource::ModEnvelope, ModDest::ShapeB,            0.30f },
        { ModSource::Current,     ModDest::OscMix,            0.30f },
        { ModSource::Drift,       ModDest::FineAll,           0.12f },
        { ModSource::Tide,        ModDest::ResonatorSize,     0.22f },
        { ModSource::Aftertouch,  ModDest::FilterCutoff,      0.35f },
    }));
}

} // namespace ripples::factory
