#include "Presets/PresetAuthoring.h"
#include "Presets/Banks.h"

/*
    RIPPLES — the BIOLUMINESCENCE bank.

    See Presets/PresetAuthoring.h for the unit helpers and the make() form, and
    docs/PRESET_GUIDE.md for what makes a preset in this bank good.
*/

namespace ripples::factory
{

//==============================================================================
//  BIOLUMINESCENCE — light made by living things. Glassy, inharmonic, glowing.
//==============================================================================
void addBioluminescenceBank (std::vector<Preset>& out)
{
    // --- DRY AQUATIC #13 ---------------------------------------------------
    out.push_back (make (kBiolum, "BIOLUMINESCENT KEYS", "Key", { "Glassy", "Dreamy", "Organic" }, Dry::Yes,
        "Bell-like, but alive. The Glass oscillator supplies the inharmonic "
        "partials and the resonator bank — large, bright, lightly scattered — "
        "supplies the glow. The soft-edged attack and long tail come from the "
        "envelopes, not from a reverb: there isn't one.",
    {
        RIPPLES_FX_BYPASSED,

        { pid::oscAWave,      wv (OscWave::Glass) },
        { pid::oscAShape,     0.58f },
        { pid::oscAUnison,    uni (3) },
        { pid::oscADetune,    0.11f },
        { pid::oscAStereo,    0.80f },
        { pid::oscALevel,     lvl (-4.0f) },

        { pid::oscBWave,      wv (OscWave::Sine) },
        { pid::oscBOctave,    oct (1) },
        { pid::oscBSemitone,  semi (7) },
        { pid::oscBFine,      cents (4.0f) },
        { pid::oscBLevel,     lvl (-15.0f) },
        { pid::oscBStereo,    0.70f },
        { pid::oscBInterMode, im (InteractionMode::PhaseMod) },
        { pid::oscBInterAmt,  0.18f },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subLevel,      lvl (-19.0f) },
        { pid::noiseType,     nz (NoiseType::Air) },
        { pid::noiseLevel,    lvl (-26.0f) },
        { pid::noiseTone,     0.82f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (2600.0f) },
        { pid::filtReso,      0.34f },
        { pid::filtDrive,     0.10f },
        { pid::filtKeyTrack,  0.80f },
        { pid::filtEnvAmt,    bip (0.42f) },
        { pid::filtPressure,  0.25f },

        { pid::fenvAttack,    att (0.030f) },
        { pid::fenvDecay,     dec (2.20f) },
        { pid::fenvSustain,   0.22f },
        { pid::fenvRelease,   rel (2.50f) },
        { pid::fenvVelocity,  0.55f },

        { pid::aenvAttack,    att (0.050f) },
        { pid::aenvDecay,     dec (4.00f) },
        { pid::aenvSustain,   0.35f },
        { pid::aenvRelease,   rel (3.50f) },
        { pid::aenvVelocity,  0.60f },

        { pid::macroGlow,     0.90f },
        { pid::macroWet,      0.55f },
        { pid::macroRipple,   0.40f },
        { pid::macroDrops,    0.30f },
        { pid::macroCurrent,  0.40f },
        { pid::fluidX,        bip (0.05f) },
        { pid::fluidY,        bip (-0.20f) },

        { pid::tideShape,     ts (TideShape::Flow) },
        { pid::tideRate,      tideHz (0.28f) },
        { pid::tideDepth,     0.38f },
        { pid::tideStereo,    0.75f },
        { pid::currRate,      currHz (0.55f) },
        { pid::currAmount,    0.45f },
        { pid::currSmooth,    0.60f },
        { pid::currStereo,    0.85f },
        { pid::driftRate,     driftHz (0.04f) },
        { pid::driftAmount,   0.35f },
        { pid::rippleRate,    rippleHz (5.0f) },
        { pid::rippleDecay,   0.70f },
        { pid::rippleDepth,   0.32f },
        { pid::rippleCycles,  cycles (4.0f) },
        { pid::rippleSpread,  0.65f },

        { pid::dropAmount,    0.26f },
        { pid::dropMode,      dm (DropletMode::Note) },
        { pid::dropDensity,   0.24f },
        { pid::dropSize,      0.30f },
        { pid::dropTone,      0.85f },
        { pid::dropSplash,    0.35f },
        { pid::dropRandom,    0.60f },
        { pid::dropSpread,    0.90f },

        { pid::resoAmount,    0.62f },
        { pid::resoSize,      0.72f },
        { pid::resoDecay,     0.74f },
        { pid::resoDamping,   0.28f },
        { pid::resoScatter,   0.38f },
        { pid::resoMotion,    0.45f },

        { pid::mastHigh,      eqdb (1.5f) },
        { pid::mastDrive,     0.06f },
    },
    {
        { ModSource::ModEnvelope,   ModDest::InteractionAmount, 0.35f },
        { ModSource::Tide,          ModDest::ResonatorSize,     0.30f },
        { ModSource::Tide,          ModDest::ShapeA,            0.30f },
        { ModSource::Current,       ModDest::ResonatorScatter,  0.35f },
        { ModSource::Current,       ModDest::FilterCutoff,      0.30f },
        { ModSource::Ripple,        ModDest::ResonatorDamping, -0.35f },
        { ModSource::Velocity,      ModDest::ResonatorAmount,   0.35f },
        { ModSource::Velocity,      ModDest::FilterCutoff,      0.40f },
        { ModSource::KeyTrack,      ModDest::ResonatorDecay,   -0.30f },
        { ModSource::RandomPerNote, ModDest::PanA,              0.25f },
        { ModSource::Aftertouch,    ModDest::ResonatorAmount,   0.30f },
    }));

    out.push_back (make (kBiolum, "GLOW PLANKTON", "Texture", { "Glassy", "Dreamy", "Organic" }, Dry::No,
        "A cloud of tiny lights. High, sparse, and never still — the Current "
        "moves shape and pan, the droplets are almost too small to hear on "
        "their own, and the delay keeps spreading them further out.",
    {
        { pid::oscAWave,      wv (OscWave::Glass) },
        { pid::oscAShape,     0.75f },
        { pid::oscAOctave,    oct (1) },
        { pid::oscAUnison,    uni (4) },
        { pid::oscADetune,    0.18f },
        { pid::oscAStereo,    0.95f },
        { pid::oscALevel,     lvl (-9.0f) },

        { pid::oscBWave,      wv (OscWave::Water) },
        { pid::oscBOctave,    oct (2) },
        { pid::oscBShape,     0.65f },
        { pid::oscBUnison,    uni (2) },
        { pid::oscBLevel,     lvl (-18.0f) },
        { pid::oscBStereo,    0.90f },

        { pid::subLevel,      lvl (-30.0f) },
        { pid::noiseType,     nz (NoiseType::Air) },
        { pid::noiseLevel,    lvl (-20.0f) },
        { pid::noiseTone,     0.90f },

        { pid::filtMode,      fm (FilterMode::BP12) },
        { pid::filtCutoff,    hz (3800.0f) },
        { pid::filtReso,      0.40f },
        { pid::filtKeyTrack,  0.60f },
        { pid::filtEnvAmt,    bip (0.25f) },
        { pid::filtMovement,  0.60f },

        { pid::fenvAttack,    att (0.60f) },
        { pid::fenvDecay,     dec (3.00f) },
        { pid::fenvSustain,   0.45f },
        { pid::fenvRelease,   rel (3.00f) },

        { pid::aenvAttack,    att (0.90f) },
        { pid::aenvDecay,     dec (3.50f) },
        { pid::aenvSustain,   0.60f },
        { pid::aenvRelease,   rel (3.50f) },
        { pid::aenvVelocity,  0.35f },

        { pid::macroGlow,     0.95f },
        { pid::macroWet,      0.55f },
        { pid::macroDrops,    0.55f },
        { pid::macroCurrent,  0.60f },
        { pid::macroSpace,    0.60f },
        { pid::fluidX,        bip (0.30f) },
        { pid::fluidY,        bip (-0.70f) },

        { pid::tideShape,     ts (TideShape::DoubleWave) },
        { pid::tideRate,      tideHz (0.65f) },
        { pid::tideDepth,     0.40f },
        { pid::tideStereo,    0.85f },
        { pid::currRate,      currHz (1.8f) },
        { pid::currAmount,    0.60f },
        { pid::currSmooth,    0.40f },
        { pid::currStereo,    0.95f },
        { pid::driftRate,     driftHz (0.09f) },
        { pid::driftAmount,   0.40f },

        { pid::dropAmount,    0.45f },
        { pid::dropDensity,   0.60f },
        { pid::dropSize,      0.15f },
        { pid::dropTone,      0.92f },
        { pid::dropSplash,    0.40f },
        { pid::dropRandom,    0.90f },
        { pid::dropSpread,    1.00f },

        { pid::resoAmount,    0.48f },
        { pid::resoSize,      0.55f },
        { pid::resoDecay,     0.60f },
        { pid::resoDamping,   0.25f },
        { pid::resoScatter,   0.70f },
        { pid::resoMotion,    0.65f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.50f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.7f) },
        { pid::chorDepth,     0.40f },
        { pid::chorMix,       0.28f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (0.48f) },
        { pid::dlyFeedback,   0.50f },
        { pid::dlyMotion,     0.55f },
        { pid::dlySpread,     0.80f },
        { pid::dlyDamping,    0.45f },
        { pid::dlyMix,        0.30f },
        { pid::diffEnable,    on },
        { pid::diffMix,       0.30f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.70f },
        { pid::verbDecay,     0.68f },
        { pid::verbHighCut,   vHighHz (14000.0f) },
        { pid::verbMix,       0.40f },

        { pid::mastLow,       eqdb (-3.0f) },
        { pid::mastHigh,      eqdb (2.5f) },
    },
    {
        { ModSource::Current,       ModDest::ShapeA,          0.50f },
        { ModSource::Current,       ModDest::PanA,            0.50f },
        { ModSource::Current,       ModDest::DropletDensity,  0.40f },
        { ModSource::Tide,          ModDest::FilterCutoff,    0.40f },
        { ModSource::Tide,          ModDest::ResonatorScatter, 0.30f },
        { ModSource::Drift,         ModDest::PanB,           -0.45f },
        { ModSource::AmpEnvelope,   ModDest::DropletAmount,   0.40f },
        { ModSource::RandomPerNote, ModDest::FineAll,         0.05f },
    }));

    out.push_back (make (kBiolum, "ANGLERFISH", "Lead", { "Dark", "Glassy", "Cinematic" }, Dry::No,
        "A dark body with one bright point in front of it: a closed LP24 on the "
        "sub-heavy layer, and a thin Glass partial riding above the cutoff that "
        "the mod wheel brings forward.",
    {
        { pid::oscAWave,      wv (OscWave::Hollow) },
        { pid::oscAShape,     0.32f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (3) },
        { pid::oscADetune,    0.16f },
        { pid::oscAStereo,    0.55f },
        { pid::oscALevel,     lvl (-4.0f) },

        { pid::oscBWave,      wv (OscWave::Glass) },
        { pid::oscBOctave,    oct (2) },
        { pid::oscBShape,     0.80f },
        { pid::oscBLevel,     lvl (-20.0f) },
        { pid::oscBStereo,    0.85f },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subLevel,      lvl (-9.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-26.0f) },
        { pid::noiseTone,     0.20f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (600.0f) },
        { pid::filtReso,      0.44f },
        { pid::filtDrive,     0.30f },
        { pid::filtKeyTrack,  0.60f },
        { pid::filtEnvAmt,    bip (0.45f) },
        { pid::filtPressure,  0.55f },

        { pid::fenvAttack,    att (0.080f) },
        { pid::fenvDecay,     dec (1.20f) },
        { pid::fenvSustain,   0.30f },
        { pid::fenvRelease,   rel (1.00f) },
        { pid::fenvVelocity,  0.60f },

        { pid::aenvAttack,    att (0.120f) },
        { pid::aenvDecay,     dec (1.80f) },
        { pid::aenvSustain,   0.80f },
        { pid::aenvRelease,   rel (1.20f) },
        { pid::aenvVelocity,  0.50f },

        { pid::macroDepth,    0.70f },
        { pid::macroGlow,     0.55f },
        { pid::macroWet,      0.45f },
        { pid::macroSpace,    0.55f },
        { pid::fluidX,        bip (-0.15f) },
        { pid::fluidY,        bip (0.60f) },

        { pid::tideShape,     ts (TideShape::Sine) },
        { pid::tideRate,      tideHz (3.2f) },
        { pid::tideDepth,     0.18f },
        { pid::currRate,      currHz (0.35f) },
        { pid::currAmount,    0.35f },
        { pid::currSmooth,    0.70f },
        { pid::driftRate,     driftHz (0.02f) },
        { pid::driftAmount,   0.30f },
        { pid::rippleRate,    rippleHz (4.5f) },
        { pid::rippleDecay,   0.70f },
        { pid::rippleDepth,   0.25f },

        { pid::resoAmount,    0.40f },
        { pid::resoSize,      0.58f },
        { pid::resoDecay,     0.66f },
        { pid::resoDamping,   0.35f },
        { pid::resoScatter,   0.35f },
        { pid::resoMotion,    0.40f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.30f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.3f) },
        { pid::chorMix,       0.22f },
        { pid::dlyEnable,     on },
        { pid::dlySync,       on },
        { pid::dlySyncTime,   sd (SyncDivision::Quarter) },
        { pid::dlyFeedback,   0.44f },
        { pid::dlyDamping,    0.66f },
        { pid::dlyMix,        0.26f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.76f },
        { pid::verbDecay,     0.72f },
        { pid::verbHighCut,   vHighHz (6000.0f) },
        { pid::verbMix,       0.36f },

        { pid::mastLow,       eqdb (1.5f) },
        { pid::mastDrive,     0.18f },
        { pid::voiceCount,    vox (2) },
        { pid::glideMode,     gmd (GlideMode::Legato) },
        { pid::glideTime,     gtime (0.12f) },
        { pid::bendRange,     bend (12) },
    },
    {
        { ModSource::ModWheel,    ModDest::LevelB,           0.60f },
        { ModSource::ModWheel,    ModDest::ResonatorAmount,  0.35f },
        { ModSource::Aftertouch,  ModDest::FilterCutoff,     0.45f },
        { ModSource::Velocity,    ModDest::FilterCutoff,     0.35f },
        { ModSource::ModEnvelope, ModDest::ShapeB,           0.40f },
        { ModSource::Ripple,      ModDest::ResonatorScatter, 0.30f },
        { ModSource::Tide,        ModDest::LevelB,           0.25f },
        { ModSource::Drift,       ModDest::FineAll,          0.12f },
    }));

    out.push_back (make (kBiolum, "JELLYFISH", "Pad", { "Dreamy", "Glassy", "Calm" }, Dry::No,
        "Pulse and glide. A Swell-shaped tide drives amplitude and cutoff "
        "together so the pad contracts and releases on its own, once every few "
        "seconds, whether or not you play anything new.",
    {
        { pid::oscAWave,      wv (OscWave::Water) },
        { pid::oscAShape,     0.60f },
        { pid::oscAUnison,    uni (5) },
        { pid::oscADetune,    0.20f },
        { pid::oscAStereo,    0.95f },
        { pid::oscALevel,     lvl (-5.0f) },

        { pid::oscBWave,      wv (OscWave::Glass) },
        { pid::oscBOctave,    oct (1) },
        { pid::oscBShape,     0.50f },
        { pid::oscBFine,      cents (-6.0f) },
        { pid::oscBUnison,    uni (3) },
        { pid::oscBDetune,    0.16f },
        { pid::oscBStereo,    0.90f },
        { pid::oscBLevel,     lvl (-14.0f) },

        { pid::subLevel,      lvl (-18.0f) },
        { pid::noiseType,     nz (NoiseType::Air) },
        { pid::noiseLevel,    lvl (-27.0f) },
        { pid::noiseTone,     0.75f },

        { pid::filtMode,      fm (FilterMode::LP12) },
        { pid::filtCutoff,    hz (2000.0f) },
        { pid::filtReso,      0.26f },
        { pid::filtKeyTrack,  0.50f },
        { pid::filtEnvAmt,    bip (0.30f) },
        { pid::filtPressure,  0.35f },

        { pid::fenvAttack,    att (1.80f) },
        { pid::fenvDecay,     dec (4.00f) },
        { pid::fenvSustain,   0.55f },
        { pid::fenvRelease,   rel (4.50f) },

        { pid::aenvAttack,    att (1.50f) },
        { pid::aenvDecay,     dec (3.50f) },
        { pid::aenvSustain,   0.85f },
        { pid::aenvRelease,   rel (5.00f) },
        { pid::aenvVelocity,  0.25f },

        { pid::macroGlow,     0.70f },
        { pid::macroWet,      0.55f },
        { pid::macroSpace,    0.70f },
        { pid::macroRipple,   0.35f },
        { pid::macroCurrent,  0.45f },
        { pid::fluidX,        bip (-0.35f) },
        { pid::fluidY,        bip (-0.10f) },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.25f) },
        { pid::tideDepth,     0.70f },
        { pid::tideStereo,    0.65f },
        { pid::currRate,      currHz (0.30f) },
        { pid::currAmount,    0.45f },
        { pid::currSmooth,    0.75f },
        { pid::driftRate,     driftHz (0.02f) },
        { pid::driftAmount,   0.45f },
        { pid::rippleRate,    rippleHz (2.5f) },
        { pid::rippleDecay,   0.65f },
        { pid::rippleDepth,   0.30f },
        { pid::rippleSpread,  0.70f },

        { pid::dropAmount,    0.20f },
        { pid::dropDensity,   0.20f },
        { pid::dropSize,      0.45f },
        { pid::dropTone,      0.75f },
        { pid::dropSpread,    0.95f },

        { pid::resoAmount,    0.44f },
        { pid::resoSize,      0.66f },
        { pid::resoDecay,     0.66f },
        { pid::resoDamping,   0.35f },
        { pid::resoScatter,   0.45f },
        { pid::resoMotion,    0.55f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.45f },
        { pid::scurRate,      scurHz (0.07f) },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.22f) },
        { pid::chorDepth,     0.50f },
        { pid::chorMix,       0.32f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (0.70f) },
        { pid::dlyFeedback,   0.42f },
        { pid::dlyMotion,     0.50f },
        { pid::dlyDamping,    0.60f },
        { pid::dlyMix,        0.24f },
        { pid::diffEnable,    on },
        { pid::diffMix,       0.32f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.80f },
        { pid::verbDecay,     0.76f },
        { pid::verbMod,       0.50f },
        { pid::verbMix,       0.44f },
    },
    {
        { ModSource::Tide,        ModDest::Amplitude,       0.45f },
        { ModSource::Tide,        ModDest::FilterCutoff,    0.40f },
        { ModSource::Tide,        ModDest::ResonatorAmount, 0.25f },
        { ModSource::Ripple,      ModDest::ShapeA,          0.30f },
        { ModSource::Current,     ModDest::OscMix,          0.30f },
        { ModSource::Drift,       ModDest::FineAll,         0.15f },
        { ModSource::Drift,       ModDest::PanB,            0.40f },
        { ModSource::ModWheel,    ModDest::ChorusDepth,     0.40f },
    }));

    // --- DRY AQUATIC #14 ---------------------------------------------------
    out.push_back (make (kBiolum, "PHOSPHOR", "Pluck", { "Bright", "Glassy", "Wet" }, Dry::Yes,
        "A struck light. Extremely short amp decay into a long, bright, "
        "undamped resonator — all of the sustain you hear is the resonator "
        "bank ringing, with no reverb or delay anywhere.",
    {
        RIPPLES_FX_BYPASSED,

        { pid::oscAWave,      wv (OscWave::Glass) },
        { pid::oscAShape,     0.72f },
        { pid::oscAUnison,    uni (2) },
        { pid::oscADetune,    0.07f },
        { pid::oscAStereo,    0.65f },
        { pid::oscALevel,     lvl (-4.0f) },
        { pid::oscAPhase,     startPhase (0.0f) },

        { pid::oscBWave,      wv (OscWave::Triangle) },
        { pid::oscBOctave,    oct (2) },
        { pid::oscBLevel,     lvl (-17.0f) },
        { pid::oscBPhase,     startPhase (0.0f) },

        { pid::subLevel,      lvl (-24.0f) },
        { pid::noiseType,     nz (NoiseType::Bubble) },
        { pid::noiseLevel,    lvl (-18.0f) },
        { pid::noiseTone,     0.88f },

        { pid::filtMode,      fm (FilterMode::BP12) },
        { pid::filtCutoff,    hz (2800.0f) },
        { pid::filtReso,      0.40f },
        { pid::filtKeyTrack,  0.85f },
        { pid::filtEnvAmt,    bip (0.60f) },
        { pid::filtMovement,  0.55f },

        { pid::fenvAttack,    att (0.001f) },
        { pid::fenvDecay,     dec (0.10f) },
        { pid::fenvSustain,   0.00f },
        { pid::fenvRelease,   rel (0.12f) },
        { pid::fenvVelocity,  0.80f },

        { pid::aenvAttack,    att (0.001f) },
        { pid::aenvDecay,     dec (0.16f) },
        { pid::aenvSustain,   0.00f },
        { pid::aenvRelease,   rel (0.14f) },
        { pid::aenvVelocity,  0.85f },

        { pid::macroGlow,     0.85f },
        { pid::macroWet,      0.60f },
        { pid::macroRipple,   0.50f },
        { pid::macroDrops,    0.40f },
        { pid::fluidX,        bip (0.25f) },
        { pid::fluidY,        bip (-0.45f) },

        { pid::tideRate,      tideHz (1.0f) },
        { pid::tideDepth,     0.20f },
        { pid::tideStereo,    0.70f },
        { pid::currRate,      currHz (1.2f) },
        { pid::currAmount,    0.40f },
        { pid::currSmooth,    0.45f },
        { pid::rippleRate,    rippleHz (16.0f) },
        { pid::rippleDecay,   0.88f },
        { pid::rippleDepth,   0.40f },
        { pid::rippleCycles,  cycles (3.0f) },
        { pid::rippleSpread,  0.70f },

        { pid::dropAmount,    0.35f },
        { pid::dropMode,      dm (DropletMode::Note) },
        { pid::dropDensity,   0.28f },
        { pid::dropSize,      0.16f },
        { pid::dropTone,      0.90f },
        { pid::dropSplash,    0.45f },
        { pid::dropBounce,    0.35f },
        { pid::dropSpread,    0.85f },

        { pid::resoAmount,    0.75f },
        { pid::resoSize,      0.58f },
        { pid::resoDecay,     0.88f },
        { pid::resoDamping,   0.15f },
        { pid::resoScatter,   0.42f },
        { pid::resoMotion,    0.50f },

        { pid::mastLow,       eqdb (-2.0f) },
        { pid::mastHigh,      eqdb (2.0f) },
        { pid::mastDrive,     0.08f },
    },
    {
        { ModSource::Velocity,      ModDest::ResonatorAmount,  0.45f },
        { ModSource::Velocity,      ModDest::ResonatorDecay,   0.30f },
        { ModSource::Velocity,      ModDest::FilterCutoff,     0.45f },
        { ModSource::Ripple,        ModDest::ResonatorScatter, 0.40f },
        { ModSource::Ripple,        ModDest::FilterCutoff,     0.35f },
        { ModSource::KeyTrack,      ModDest::ResonatorDecay,  -0.35f },
        { ModSource::Current,       ModDest::ResonatorSize,    0.25f },
        { ModSource::RandomPerNote, ModDest::PanA,             0.45f },
        { ModSource::RandomPerNote, ModDest::ResonatorSize,    0.15f },
    }));
}

} // namespace ripples::factory
