#include "Presets/PresetAuthoring.h"
#include "Presets/Banks.h"

/*
    RIPPLES — the THE ABYSS bank.

    See Presets/PresetAuthoring.h for the unit helpers and the make() form, and
    docs/PRESET_GUIDE.md for what makes a preset in this bank good.
*/

namespace ripples::factory
{

//==============================================================================
//  THE ABYSS — no light. Sub weight, closed filters, enormous slow spaces.
//==============================================================================
void addAbyssBank (std::vector<Preset>& out)
{
    // --- DRY AQUATIC #7 ----------------------------------------------------
    out.push_back (make (kAbyss, "ABYSS BASS", "Bass", { "Deep", "Dark", "Submerged" }, Dry::Yes,
        "A PLAYED bass, not a drone: mono legato, full key tracking so it stays "
        "in tune up the neck, a tight mod envelope on a resonant LP24 at 180 Hz, "
        "and a note-mode droplet per attack for the gulp. Compare OCEAN FLOOR, "
        "which is the same depth with none of the articulation.",
    {
        RIPPLES_FX_BYPASSED,

        { pid::oscAWave,      wv (OscWave::Hollow) },
        { pid::oscAShape,     0.28f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (1) },
        { pid::oscAStereo,    0.20f },
        { pid::oscALevel,     lvl (-2.0f) },
        { pid::oscAPhase,     startPhase (0.0f) },   // identical attack every note

        { pid::oscBWave,      wv (OscWave::Water) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBShape,     0.35f },
        { pid::oscBFine,      cents (-8.0f) },
        { pid::oscBLevel,     lvl (-8.0f) },
        { pid::oscBStereo,    0.25f },
        { pid::oscBPhase,     startPhase (0.0f) },

        { pid::subWave,       sw (SubWave::Triangle) },
        { pid::subOctave,     subOct (-1) },
        { pid::subLevel,      lvl (-5.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-24.0f) },
        { pid::noiseTone,     0.18f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (180.0f) },
        { pid::filtReso,      0.55f },
        { pid::filtDrive,     0.35f },
        { pid::filtKeyTrack,  1.00f },
        { pid::filtEnvAmt,    bip (0.62f) },
        { pid::filtPressure,  0.60f },

        { pid::fenvAttack,    att (0.001f) },
        { pid::fenvDecay,     dec (0.38f) },
        { pid::fenvSustain,   0.15f },
        { pid::fenvRelease,   rel (0.30f) },
        { pid::fenvVelocity,  0.70f },

        { pid::aenvAttack,    att (0.003f) },
        { pid::aenvDecay,     dec (1.20f) },
        { pid::aenvSustain,   0.70f },
        { pid::aenvRelease,   rel (0.28f) },
        { pid::aenvVelocity,  0.55f },

        { pid::macroDepth,    0.90f },
        { pid::macroPressure, 0.65f },
        { pid::macroWet,      0.40f },
        { pid::macroDrops,    0.35f },
        { pid::macroRipple,   0.45f },
        { pid::macroGlow,     0.10f },
        { pid::fluidX,        bip (-0.20f) },
        { pid::fluidY,        bip (0.75f) },
        { pid::fluidYAmount,  0.70f },

        { pid::tideRate,      tideHz (0.40f) },
        { pid::tideDepth,     0.14f },
        { pid::tideStereo,    0.20f },
        { pid::currRate,      currHz (0.55f) },
        { pid::currAmount,    0.28f },
        { pid::currSmooth,    0.70f },
        { pid::currStereo,    0.30f },
        { pid::driftRate,     driftHz (0.03f) },
        { pid::driftAmount,   0.20f },
        { pid::rippleRate,    rippleHz (5.5f) },
        { pid::rippleDecay,   0.78f },
        { pid::rippleDepth,   0.48f },
        { pid::rippleCycles,  cycles (3.0f) },
        { pid::rippleTrigger, rtg (RippleTrigger::NoteOn) },

        { pid::dropAmount,    0.30f },
        { pid::dropMode,      dm (DropletMode::Note) },
        { pid::dropDensity,   0.22f },
        { pid::dropSize,      0.85f },
        { pid::dropTone,      0.15f },
        { pid::dropSplash,    0.25f },
        { pid::dropGravity,   0.70f },
        { pid::dropBounce,    0.20f },
        { pid::dropRandom,    0.25f },
        { pid::dropSpread,    0.40f },

        { pid::resoAmount,    0.24f },
        { pid::resoSize,      0.30f },
        { pid::resoDecay,     0.28f },
        { pid::resoDamping,   0.82f },
        { pid::resoScatter,   0.15f },
        { pid::resoMotion,    0.10f },

        { pid::mastLow,       eqdb (2.5f) },
        { pid::mastMid,       eqdb (-1.5f) },
        { pid::mastHigh,      eqdb (-3.0f) },
        { pid::mastDrive,     0.24f },
        { pid::mastCeiling,   ceildb (-0.5f) },

        { pid::voiceCount,    vox (1) },
        { pid::glideMode,     gmd (GlideMode::Legato) },
        { pid::glideTime,     gtime (0.05f) },
    },
    {
        { ModSource::Ripple,      ModDest::FilterCutoff,  0.40f },
        { ModSource::Ripple,      ModDest::DropletTone,   0.25f },
        { ModSource::Velocity,    ModDest::FilterCutoff,  0.45f },
        { ModSource::Velocity,    ModDest::FilterDrive,   0.30f },
        { ModSource::Velocity,    ModDest::DropletAmount, 0.40f },
        { ModSource::ModEnvelope, ModDest::NoiseLevel,    0.45f },
        { ModSource::ModEnvelope, ModDest::ShapeA,        0.30f },
        { ModSource::Current,     ModDest::FilterCutoff,  0.15f },
        { ModSource::ModWheel,    ModDest::FilterResonance, 0.30f },
        { ModSource::KeyTrack,    ModDest::SubLevel,     -0.35f },
    }));

    // --- DRY AQUATIC #8 ----------------------------------------------------
    out.push_back (make (kAbyss, "OCEAN FLOOR", "Drone", { "Deep", "Dark", "Cinematic" }, Dry::Yes,
        "Mass and stillness. No attack, no articulation, no effects — the room "
        "is the resonator, held at maximum size and decay with heavy damping, "
        "and the only motion is Drift moving a nearly closed filter. The "
        "opposite pole to ABYSS BASS.",
    {
        RIPPLES_FX_BYPASSED,

        { pid::oscAWave,      wv (OscWave::Water) },
        { pid::oscAShape,     0.22f },
        { pid::oscAOctave,    oct (-2) },
        { pid::oscAUnison,    uni (6) },
        { pid::oscADetune,    0.34f },
        { pid::oscAStereo,    0.95f },
        { pid::oscALevel,     lvl (-5.0f) },

        { pid::oscBWave,      wv (OscWave::Hollow) },
        { pid::oscBOctave,    oct (-2) },
        { pid::oscBSemitone,  semi (7) },
        { pid::oscBFine,      cents (-17.0f) },
        { pid::oscBUnison,    uni (4) },
        { pid::oscBDetune,    0.30f },
        { pid::oscBStereo,    0.95f },
        { pid::oscBLevel,     lvl (-11.0f) },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subOctave,     subOct (-2) },
        { pid::subLevel,      lvl (-8.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-18.0f) },
        { pid::noiseTone,     0.06f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (150.0f) },
        { pid::filtReso,      0.18f },
        { pid::filtDrive,     0.22f },
        { pid::filtKeyTrack,  0.15f },
        { pid::filtEnvAmt,    bip (0.12f) },
        { pid::filtPressure,  0.85f },

        { pid::fenvAttack,    att (6.00f) },
        { pid::fenvDecay,     dec (15.00f) },
        { pid::fenvSustain,   0.80f },
        { pid::fenvRelease,   rel (12.00f) },
        { pid::fenvVelocity,  0.10f },

        { pid::aenvAttack,    att (5.00f) },
        { pid::aenvDecay,     dec (12.00f) },
        { pid::aenvSustain,   1.00f },
        { pid::aenvRelease,   rel (14.00f) },
        { pid::aenvVelocity,  0.10f },

        { pid::macroDepth,    1.00f },
        { pid::macroPressure, 0.85f },
        { pid::macroWet,      0.55f },
        { pid::macroCurrent,  0.35f },
        { pid::macroDrops,    0.20f },
        { pid::macroGlow,     0.00f },
        { pid::fluidX,        bip (-0.70f) },
        { pid::fluidY,        bip (1.00f) },
        { pid::fluidYAmount,  0.90f },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.03f) },
        { pid::tideDepth,     0.55f },
        { pid::tideStereo,    0.50f },
        { pid::currRate,      currHz (0.06f) },
        { pid::currAmount,    0.40f },
        { pid::currSmooth,    0.95f },
        { pid::currDrift,     0.60f },
        { pid::currStereo,    0.85f },
        { pid::driftRate,     driftHz (0.004f) },
        { pid::driftAmount,   0.75f },
        { pid::driftStereo,   0.90f },
        { pid::rippleDepth,   0.00f },

        { pid::dropAmount,    0.20f },
        { pid::dropDensity,   0.08f },
        { pid::dropSize,      0.95f },
        { pid::dropTone,      0.10f },
        { pid::dropSplash,    0.15f },
        { pid::dropGravity,   0.30f },
        { pid::dropBounce,    0.10f },
        { pid::dropRandom,    0.80f },
        { pid::dropSpread,    0.90f },

        { pid::resoAmount,    0.50f },
        { pid::resoSize,      1.00f },
        { pid::resoDecay,     0.92f },
        { pid::resoDamping,   0.85f },
        { pid::resoScatter,   0.35f },
        { pid::resoMotion,    0.25f },

        { pid::mastLow,       eqdb (3.5f) },
        { pid::mastMid,       eqdb (-2.0f) },
        { pid::mastHigh,      eqdb (-6.0f) },
        { pid::mastDrive,     0.18f },
        { pid::voiceCount,    vox (6) },
    },
    {
        { ModSource::Drift,   ModDest::FilterCutoff,   0.45f },
        { ModSource::Drift,   ModDest::FineAll,        0.30f },
        { ModSource::Drift,   ModDest::ResonatorSize,  0.25f },
        { ModSource::Tide,    ModDest::Amplitude,      0.22f },
        { ModSource::Tide,    ModDest::NoiseLevel,     0.40f },
        { ModSource::Current, ModDest::NoiseTone,      0.30f },
        { ModSource::Current, ModDest::PanA,           0.45f },
        { ModSource::Current, ModDest::ResonatorDamping, 0.25f },
        { ModSource::ModWheel, ModDest::FilterCutoff,  0.35f },
    }));

    out.push_back (make (kAbyss, "PRESSURE", "Bass", { "Dark", "Deep", "Chaotic" }, Dry::No,
        "Hard-synced and driven. Osc B is the master sync source, so the shape "
        "control becomes a formant sweep instead of a PWM — an aggressive bass "
        "that still lives below the waterline.",
    {
        { pid::oscAWave,      wv (OscWave::Saw) },
        { pid::oscAShape,     0.45f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (2) },
        { pid::oscADetune,    0.10f },
        { pid::oscAStereo,    0.35f },
        { pid::oscALevel,     lvl (-3.0f) },
        { pid::oscAPhase,     startPhase (0.0f) },

        { pid::oscBWave,      wv (OscWave::Shark) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBShape,     0.40f },
        { pid::oscBLevel,     lvl (-10.0f) },
        { pid::oscBInterMode, im (InteractionMode::HardSync) },
        { pid::oscBInterAmt,  0.55f },

        { pid::subWave,       sw (SubWave::Square) },
        { pid::subLevel,      lvl (-7.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-26.0f) },
        { pid::noiseTone,     0.25f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (260.0f) },
        { pid::filtReso,      0.48f },
        { pid::filtDrive,     0.55f },
        { pid::filtKeyTrack,  0.90f },
        { pid::filtEnvAmt,    bip (0.70f) },
        { pid::filtPressure,  0.75f },

        { pid::fenvAttack,    att (0.001f) },
        { pid::fenvDecay,     dec (0.24f) },
        { pid::fenvSustain,   0.10f },
        { pid::fenvRelease,   rel (0.22f) },
        { pid::fenvVelocity,  0.75f },

        { pid::aenvAttack,    att (0.002f) },
        { pid::aenvDecay,     dec (0.80f) },
        { pid::aenvSustain,   0.65f },
        { pid::aenvRelease,   rel (0.20f) },
        { pid::aenvVelocity,  0.60f },

        { pid::macroDepth,    0.80f },
        { pid::macroPressure, 0.85f },
        { pid::macroRipple,   0.35f },
        { pid::macroWet,      0.25f },
        { pid::fluidX,        bip (0.40f) },
        { pid::fluidY,        bip (0.65f) },

        { pid::tideRate,      tideHz (0.6f) },
        { pid::tideDepth,     0.20f },
        { pid::currRate,      currHz (1.1f) },
        { pid::currAmount,    0.35f },
        { pid::currSmooth,    0.40f },
        { pid::rippleRate,    rippleHz (8.0f) },
        { pid::rippleDecay,   0.80f },
        { pid::rippleDepth,   0.40f },

        { pid::resoAmount,    0.18f },
        { pid::resoSize,      0.26f },
        { pid::resoDecay,     0.24f },
        { pid::resoDamping,   0.80f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.18f },
        { pid::scurWidth,     0.35f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.30f },
        { pid::diffMix,       0.16f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.40f },
        { pid::verbDecay,     0.35f },
        { pid::verbLowCut,    vLowHz (400.0f) },
        { pid::verbMix,       0.14f },

        { pid::mastLow,       eqdb (2.0f) },
        { pid::mastMid,       eqdb (-2.0f) },
        { pid::mastDrive,     0.38f },
        { pid::mastCeiling,   ceildb (-0.8f) },
        { pid::voiceCount,    vox (1) },
        { pid::glideMode,     gmd (GlideMode::Legato) },
        { pid::glideTime,     gtime (0.03f) },
    },
    {
        { ModSource::ModEnvelope, ModDest::InteractionAmount, 0.55f },
        { ModSource::ModEnvelope, ModDest::ShapeB,            0.40f },
        { ModSource::Velocity,    ModDest::InteractionAmount, 0.35f },
        { ModSource::Velocity,    ModDest::FilterDrive,       0.35f },
        { ModSource::Ripple,      ModDest::PitchB,            0.12f },
        { ModSource::Current,     ModDest::FilterResonance,   0.25f },
        { ModSource::ModWheel,    ModDest::InteractionAmount, 0.45f },
    }));

    out.push_back (make (kAbyss, "TRENCH", "Pad", { "Dark", "Deep", "Cinematic" }, Dry::No,
        "A pad with the top three octaves removed. Notch filter and a heavy "
        "low shelf leave a hollow in the middle of the spectrum that the reverb "
        "fills in.",
    {
        { pid::oscAWave,      wv (OscWave::Saw) },
        { pid::oscAShape,     0.40f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (7) },
        { pid::oscADetune,    0.32f },
        { pid::oscAStereo,    1.00f },
        { pid::oscALevel,     lvl (-6.0f) },

        { pid::oscBWave,      wv (OscWave::Hollow) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBFine,      cents (12.0f) },
        { pid::oscBUnison,    uni (4) },
        { pid::oscBDetune,    0.28f },
        { pid::oscBStereo,    0.95f },
        { pid::oscBLevel,     lvl (-9.0f) },

        { pid::subLevel,      lvl (-11.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-24.0f) },
        { pid::noiseTone,     0.15f },

        { pid::filtMode,      fm (FilterMode::Notch) },
        { pid::filtCutoff,    hz (700.0f) },
        { pid::filtReso,      0.55f },
        { pid::filtDrive,     0.20f },
        { pid::filtKeyTrack,  0.30f },
        { pid::filtEnvAmt,    bip (-0.30f) },
        { pid::filtPressure,  0.70f },

        { pid::fenvAttack,    att (3.00f) },
        { pid::fenvDecay,     dec (7.00f) },
        { pid::fenvSustain,   0.45f },
        { pid::fenvRelease,   rel (7.00f) },

        { pid::aenvAttack,    att (2.20f) },
        { pid::aenvDecay,     dec (5.00f) },
        { pid::aenvSustain,   0.90f },
        { pid::aenvRelease,   rel (7.50f) },
        { pid::aenvVelocity,  0.20f },

        { pid::macroDepth,    0.85f },
        { pid::macroPressure, 0.70f },
        { pid::macroSpace,    0.85f },
        { pid::macroWet,      0.55f },
        { pid::macroGlow,     0.10f },
        { pid::fluidX,        bip (-0.45f) },
        { pid::fluidY,        bip (0.85f) },

        { pid::tideShape,     ts (TideShape::Flow) },
        { pid::tideRate,      tideHz (0.08f) },
        { pid::tideDepth,     0.45f },
        { pid::tideStereo,    0.70f },
        { pid::currRate,      currHz (0.14f) },
        { pid::currAmount,    0.50f },
        { pid::currSmooth,    0.85f },
        { pid::driftRate,     driftHz (0.01f) },
        { pid::driftAmount,   0.60f },

        { pid::resoAmount,    0.30f },
        { pid::resoSize,      0.85f },
        { pid::resoDecay,     0.75f },
        { pid::resoDamping,   0.70f },
        { pid::resoScatter,   0.40f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.42f },
        { pid::scurRate,      scurHz (0.05f) },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.14f) },
        { pid::chorDepth,     0.50f },
        { pid::chorMix,       0.28f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (1.10f) },
        { pid::dlyFeedback,   0.48f },
        { pid::dlyDamping,    0.80f },
        { pid::dlyMix,        0.22f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.60f },
        { pid::diffMix,       0.34f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.92f },
        { pid::verbDecay,     0.88f },
        { pid::verbPredelay,  pre (70.0f) },
        { pid::verbDamping,   0.65f },
        { pid::verbLowCut,    vLowHz (80.0f) },
        { pid::verbHighCut,   vHighHz (4500.0f) },
        { pid::verbMod,       0.40f },
        { pid::verbMix,       0.52f },

        { pid::mastLow,       eqdb (2.5f) },
        { pid::mastHigh,      eqdb (-5.0f) },
    },
    {
        { ModSource::Tide,     ModDest::FilterCutoff,  0.40f },
        { ModSource::Drift,    ModDest::FilterCutoff,  0.35f },
        { ModSource::Drift,    ModDest::FineAll,       0.25f },
        { ModSource::Current,  ModDest::FilterResonance, 0.25f },
        { ModSource::Current,  ModDest::PanB,          0.45f },
        { ModSource::ModWheel, ModDest::FilterCutoff,  0.45f },
        { ModSource::Velocity, ModDest::Amplitude,     0.20f },
    }));

    out.push_back (make (kAbyss, "BLACK SMOKER", "Texture", { "Dark", "Chaotic", "Deep" }, Dry::No,
        "A hydrothermal vent. Ring-modulated Shark against a driven filter, with "
        "Current pushing everything around fast enough to stay unstable.",
    {
        { pid::oscAWave,      wv (OscWave::Shark) },
        { pid::oscAShape,     0.62f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (3) },
        { pid::oscADetune,    0.35f },
        { pid::oscAStereo,    0.80f },
        { pid::oscALevel,     lvl (-8.0f) },

        { pid::oscBWave,      wv (OscWave::Pulse) },
        { pid::oscBShape,     0.22f },
        { pid::oscBSemitone,  semi (-5) },
        { pid::oscBLevel,     lvl (-14.0f) },
        { pid::oscBInterMode, im (InteractionMode::RingMod) },
        { pid::oscBInterAmt,  0.60f },

        { pid::subLevel,      lvl (-12.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-12.0f) },
        { pid::noiseTone,     0.32f },

        { pid::filtMode,      fm (FilterMode::BP12) },
        { pid::filtCutoff,    hz (420.0f) },
        { pid::filtReso,      0.60f },
        { pid::filtDrive,     0.62f },
        { pid::filtKeyTrack,  0.35f },
        { pid::filtEnvAmt,    bip (0.40f) },
        { pid::filtMovement,  0.45f },
        { pid::filtPressure,  0.65f },

        { pid::fenvAttack,    att (0.30f) },
        { pid::fenvDecay,     dec (2.00f) },
        { pid::fenvSustain,   0.40f },
        { pid::fenvRelease,   rel (2.50f) },

        { pid::aenvAttack,    att (0.60f) },
        { pid::aenvDecay,     dec (2.50f) },
        { pid::aenvSustain,   0.75f },
        { pid::aenvRelease,   rel (3.00f) },
        { pid::aenvVelocity,  0.35f },

        { pid::macroDepth,    0.75f },
        { pid::macroPressure, 0.80f },
        { pid::macroCurrent,  0.85f },
        { pid::macroDrops,    0.45f },
        { pid::macroWet,      0.45f },
        { pid::fluidX,        bip (0.80f) },
        { pid::fluidY,        bip (0.70f) },
        { pid::fluidXAmount,  0.85f },

        { pid::tideShape,     ts (TideShape::DoubleWave) },
        { pid::tideRate,      tideHz (0.9f) },
        { pid::tideDepth,     0.45f },
        { pid::tideStereo,    0.65f },
        { pid::currRate,      currHz (2.6f) },
        { pid::currAmount,    0.85f },
        { pid::currSmooth,    0.25f },
        { pid::currDrift,     0.55f },
        { pid::currStereo,    0.85f },
        { pid::driftRate,     driftHz (0.15f) },
        { pid::driftAmount,   0.45f },

        { pid::dropAmount,    0.38f },
        { pid::dropDensity,   0.55f },
        { pid::dropSize,      0.70f },
        { pid::dropTone,      0.28f },
        { pid::dropSplash,    0.70f },
        { pid::dropRandom,    0.95f },
        { pid::dropSpread,    0.80f },

        { pid::resoAmount,    0.32f },
        { pid::resoSize,      0.40f },
        { pid::resoDecay,     0.55f },
        { pid::resoDamping,   0.55f },
        { pid::resoScatter,   0.80f },
        { pid::resoMotion,    0.75f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.50f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (0.30f) },
        { pid::dlyFeedback,   0.55f },
        { pid::dlyMotion,     0.65f },
        { pid::dlyDamping,    0.60f },
        { pid::dlyMix,        0.24f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.65f },
        { pid::diffMix,       0.34f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.75f },
        { pid::verbDecay,     0.72f },
        { pid::verbDamping,   0.60f },
        { pid::verbMix,       0.38f },

        { pid::mastLow,       eqdb (1.0f) },
        { pid::mastHigh,      eqdb (-3.0f) },
        { pid::mastDrive,     0.30f },
        { pid::mastCeiling,   ceildb (-1.0f) },
    },
    {
        { ModSource::Current,     ModDest::FilterCutoff,      0.70f },
        { ModSource::Current,     ModDest::InteractionAmount, 0.50f },
        { ModSource::Current,     ModDest::ResonatorScatter,  0.55f },
        { ModSource::Tide,        ModDest::PitchB,            0.10f },
        { ModSource::Tide,        ModDest::FilterMovement,    0.45f },
        { ModSource::Drift,       ModDest::NoiseTone,         0.40f },
        { ModSource::ModEnvelope, ModDest::FilterDrive,       0.35f },
        { ModSource::RandomPerNote, ModDest::PitchB,          0.08f },
        { ModSource::ModWheel,    ModDest::DropletDensity,    0.50f },
    }));

    out.push_back (make (kAbyss, "LEVIATHAN", "Lead", { "Dark", "Deep", "Cinematic" }, Dry::No,
        "A mono lead with a slow portamento — something very large moving past. "
        "Aftertouch opens the filter and pushes the drive, so it can be played "
        "as a swell rather than as notes.",
    {
        { pid::oscAWave,      wv (OscWave::Saw) },
        { pid::oscAShape,     0.50f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (4) },
        { pid::oscADetune,    0.16f },
        { pid::oscAStereo,    0.60f },
        { pid::oscALevel,     lvl (-3.0f) },

        { pid::oscBWave,      wv (OscWave::Hollow) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBFine,      cents (-10.0f) },
        { pid::oscBUnison,    uni (2) },
        { pid::oscBDetune,    0.14f },
        { pid::oscBLevel,     lvl (-6.0f) },

        { pid::subLevel,      lvl (-10.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-25.0f) },
        { pid::noiseTone,     0.20f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (520.0f) },
        { pid::filtReso,      0.40f },
        { pid::filtDrive,     0.38f },
        { pid::filtKeyTrack,  0.55f },
        { pid::filtEnvAmt,    bip (0.35f) },
        { pid::filtPressure,  0.60f },

        { pid::fenvAttack,    att (0.20f) },
        { pid::fenvDecay,     dec (1.50f) },
        { pid::fenvSustain,   0.35f },
        { pid::fenvRelease,   rel (1.20f) },
        { pid::fenvVelocity,  0.50f },

        { pid::aenvAttack,    att (0.25f) },
        { pid::aenvDecay,     dec (2.00f) },
        { pid::aenvSustain,   0.88f },
        { pid::aenvRelease,   rel (1.40f) },
        { pid::aenvVelocity,  0.40f },

        { pid::macroDepth,    0.75f },
        { pid::macroPressure, 0.60f },
        { pid::macroWet,      0.45f },
        { pid::macroSpace,    0.60f },
        { pid::fluidX,        bip (-0.10f) },
        { pid::fluidY,        bip (0.70f) },

        { pid::tideShape,     ts (TideShape::Sine) },
        { pid::tideRate,      tideHz (4.5f) },
        { pid::tideDepth,     0.12f },
        { pid::currRate,      currHz (0.4f) },
        { pid::currAmount,    0.30f },
        { pid::currSmooth,    0.70f },
        { pid::driftRate,     driftHz (0.02f) },
        { pid::driftAmount,   0.30f },

        { pid::resoAmount,    0.22f },
        { pid::resoSize,      0.55f },
        { pid::resoDecay,     0.50f },
        { pid::resoDamping,   0.68f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.30f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.25f) },
        { pid::chorDepth,     0.35f },
        { pid::chorMix,       0.22f },
        { pid::dlyEnable,     on },
        { pid::dlySync,       on },
        { pid::dlySyncTime,   sd (SyncDivision::QuarterD) },
        { pid::dlyFeedback,   0.42f },
        { pid::dlyDamping,    0.70f },
        { pid::dlyMix,        0.24f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.80f },
        { pid::verbDecay,     0.76f },
        { pid::verbHighCut,   vHighHz (5000.0f) },
        { pid::verbMix,       0.34f },

        { pid::mastLow,       eqdb (2.0f) },
        { pid::mastHigh,      eqdb (-2.0f) },
        { pid::mastDrive,     0.22f },
        { pid::voiceCount,    vox (1) },
        { pid::glideMode,     gmd (GlideMode::Always) },
        { pid::glideTime,     gtime (0.28f) },
        { pid::bendRange,     bend (12) },
    },
    {
        { ModSource::Aftertouch,  ModDest::FilterCutoff, 0.55f },
        { ModSource::Aftertouch,  ModDest::FilterDrive,  0.35f },
        { ModSource::Aftertouch,  ModDest::Amplitude,    0.15f },
        { ModSource::ModWheel,    ModDest::PitchAll,     0.02f },
        { ModSource::Tide,        ModDest::PitchAll,     0.04f },
        { ModSource::Velocity,    ModDest::FilterCutoff, 0.35f },
        { ModSource::ModEnvelope, ModDest::ShapeA,       0.30f },
        { ModSource::Drift,       ModDest::FineAll,      0.15f },
    }));
}

} // namespace ripples::factory
