#include "Presets/PresetAuthoring.h"
#include "Presets/Banks.h"

/*
    RIPPLES — the STORMS bank.

    See Presets/PresetAuthoring.h for the unit helpers and the make() form, and
    docs/PRESET_GUIDE.md for what makes a preset in this bank good.
*/

namespace ripples::factory
{

//==============================================================================
//  STORMS — weather. Loud, unstable, driven. The chaos end of the Fluid Field.
//==============================================================================
void addStormsBank (std::vector<Preset>& out)
{
    out.push_back (make (kStorms, "SQUALL", "Texture", { "Chaotic", "Dark", "Surface" }, Dry::No,
        "Wind over water. Almost entirely noise: a band-pass sweeping fast under "
        "Current, with the oscillators only thick enough to give it a key.",
    {
        { pid::oscAWave,      wv (OscWave::Shark) },
        { pid::oscAShape,     0.55f },
        { pid::oscAUnison,    uni (4) },
        { pid::oscADetune,    0.38f },
        { pid::oscAStereo,    0.90f },
        { pid::oscALevel,     lvl (-14.0f) },

        { pid::oscBWave,      wv (OscWave::Water) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBUnison,    uni (2) },
        { pid::oscBLevel,     lvl (-18.0f) },

        { pid::subLevel,      lvl (-22.0f) },
        { pid::noiseType,     nz (NoiseType::Surf) },
        { pid::noiseLevel,    lvl (-2.0f) },
        { pid::noiseTone,     0.55f },

        { pid::filtMode,      fm (FilterMode::BP12) },
        { pid::filtCutoff,    hz (900.0f) },
        { pid::filtReso,      0.52f },
        { pid::filtDrive,     0.35f },
        { pid::filtKeyTrack,  0.20f },
        { pid::filtEnvAmt,    bip (0.30f) },
        { pid::filtMovement,  0.50f },
        { pid::filtPressure,  0.55f },

        { pid::fenvAttack,    att (0.40f) },
        { pid::fenvDecay,     dec (2.50f) },
        { pid::fenvSustain,   0.50f },
        { pid::fenvRelease,   rel (2.50f) },

        { pid::aenvAttack,    att (0.80f) },
        { pid::aenvDecay,     dec (3.00f) },
        { pid::aenvSustain,   0.80f },
        { pid::aenvRelease,   rel (3.00f) },
        { pid::aenvVelocity,  0.30f },

        { pid::macroCurrent,  0.90f },
        { pid::macroWet,      0.55f },
        { pid::macroPressure, 0.60f },
        { pid::macroSpace,    0.55f },
        { pid::fluidX,        bip (0.85f) },
        { pid::fluidY,        bip (-0.30f) },
        { pid::fluidXAmount,  0.90f },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.30f) },
        { pid::tideDepth,     0.65f },
        { pid::tideStereo,    0.80f },
        { pid::currRate,      currHz (4.0f) },
        { pid::currAmount,    0.90f },
        { pid::currSmooth,    0.25f },
        { pid::currDrift,     0.55f },
        { pid::currStereo,    0.95f },
        { pid::driftRate,     driftHz (0.20f) },
        { pid::driftAmount,   0.50f },

        { pid::dropAmount,    0.35f },
        { pid::dropDensity,   0.85f },
        { pid::dropSize,      0.20f },
        { pid::dropTone,      0.70f },
        { pid::dropSplash,    0.80f },
        { pid::dropRandom,    1.00f },
        { pid::dropSpread,    1.00f },

        { pid::resoAmount,    0.22f },
        { pid::resoSize,      0.45f },
        { pid::resoDecay,     0.35f },
        { pid::resoDamping,   0.60f },
        { pid::resoScatter,   0.85f },
        { pid::resoMotion,    0.80f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.55f },
        { pid::scurRate,      scurHz (0.35f) },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (0.28f) },
        { pid::dlyFeedback,   0.50f },
        { pid::dlyMotion,     0.70f },
        { pid::dlySpread,     0.80f },
        { pid::dlyMix,        0.22f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.70f },
        { pid::diffMix,       0.36f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.72f },
        { pid::verbDecay,     0.66f },
        { pid::verbMix,       0.34f },

        { pid::mastLow,       eqdb (-2.0f) },
        { pid::mastDrive,     0.22f },
        { pid::mastCeiling,   ceildb (-1.0f) },
    },
    {
        { ModSource::Current,     ModDest::FilterCutoff,   0.80f },
        { ModSource::Current,     ModDest::NoiseTone,      0.50f },
        { ModSource::Current,     ModDest::PanA,           0.50f },
        { ModSource::Tide,        ModDest::NoiseLevel,     0.50f },
        { ModSource::Tide,        ModDest::FilterResonance, 0.25f },
        { ModSource::Drift,       ModDest::FilterCutoff,   0.35f },
        { ModSource::Drift,       ModDest::DropletDensity, 0.45f },
        { ModSource::ModWheel,    ModDest::FilterCutoff,   0.45f },
    }));

    // --- DRY AQUATIC #15 ---------------------------------------------------
    out.push_back (make (kStorms, "BREAKERS", "FX", { "Chaotic", "Organic", "Surface" }, Dry::Yes,
        "Waves arriving. The Swell tide shape does the work — slow rise, fast "
        "fall — driving noise level, cutoff and droplet density together, so "
        "each cycle builds and collapses. Completely dry.",
    {
        RIPPLES_FX_BYPASSED,

        { pid::oscAWave,      wv (OscWave::Water) },
        { pid::oscAShape,     0.40f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (5) },
        { pid::oscADetune,    0.32f },
        { pid::oscAStereo,    1.00f },
        { pid::oscALevel,     lvl (-12.0f) },

        { pid::oscBWave,      wv (OscWave::Hollow) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBFine,      cents (-15.0f) },
        { pid::oscBUnison,    uni (3) },
        { pid::oscBStereo,    0.95f },
        { pid::oscBLevel,     lvl (-16.0f) },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subLevel,      lvl (-14.0f) },
        { pid::noiseType,     nz (NoiseType::Surf) },
        { pid::noiseLevel,    lvl (-3.0f) },
        { pid::noiseTone,     0.42f },

        { pid::filtMode,      fm (FilterMode::LP12) },
        { pid::filtCutoff,    hz (700.0f) },
        { pid::filtReso,      0.36f },
        { pid::filtDrive,     0.28f },
        { pid::filtKeyTrack,  0.20f },
        { pid::filtEnvAmt,    bip (0.30f) },
        { pid::filtPressure,  0.60f },

        { pid::fenvAttack,    att (1.20f) },
        { pid::fenvDecay,     dec (4.00f) },
        { pid::fenvSustain,   0.60f },
        { pid::fenvRelease,   rel (4.00f) },

        { pid::aenvAttack,    att (1.80f) },
        { pid::aenvDecay,     dec (4.00f) },
        { pid::aenvSustain,   0.85f },
        { pid::aenvRelease,   rel (5.00f) },
        { pid::aenvVelocity,  0.20f },

        { pid::macroWet,      0.75f },
        { pid::macroCurrent,  0.65f },
        { pid::macroDrops,    0.60f },
        { pid::macroPressure, 0.60f },
        { pid::macroDepth,    0.50f },
        { pid::fluidX,        bip (0.60f) },
        { pid::fluidY,        bip (0.10f) },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.13f) },
        { pid::tideDepth,     0.90f },
        { pid::tideStereo,    0.65f },
        { pid::currRate,      currHz (1.6f) },
        { pid::currAmount,    0.70f },
        { pid::currSmooth,    0.35f },
        { pid::currDrift,     0.45f },
        { pid::currStereo,    0.95f },
        { pid::driftRate,     driftHz (0.05f) },
        { pid::driftAmount,   0.45f },
        { pid::rippleRate,    rippleHz (2.0f) },
        { pid::rippleDecay,   0.60f },
        { pid::rippleDepth,   0.35f },
        { pid::rippleCycles,  cycles (6.0f) },

        { pid::dropAmount,    0.55f },
        { pid::dropDensity,   0.65f },
        { pid::dropSize,      0.35f },
        { pid::dropTone,      0.55f },
        { pid::dropSplash,    0.85f },
        { pid::dropGravity,   0.45f },
        { pid::dropBounce,    0.30f },
        { pid::dropRandom,    0.95f },
        { pid::dropSpread,    1.00f },

        { pid::resoAmount,    0.30f },
        { pid::resoSize,      0.70f },
        { pid::resoDecay,     0.50f },
        { pid::resoDamping,   0.65f },
        { pid::resoScatter,   0.60f },
        { pid::resoMotion,    0.60f },

        { pid::mastLow,       eqdb (1.0f) },
        { pid::mastDrive,     0.16f },
    },
    {
        { ModSource::Tide,        ModDest::NoiseLevel,     0.70f },
        { ModSource::Tide,        ModDest::FilterCutoff,   0.60f },
        { ModSource::Tide,        ModDest::DropletDensity, 0.55f },
        { ModSource::Tide,        ModDest::Amplitude,      0.25f },
        { ModSource::Current,     ModDest::NoiseTone,      0.45f },
        { ModSource::Current,     ModDest::PanA,           0.50f },
        { ModSource::Drift,       ModDest::FilterCutoff,   0.30f },
        { ModSource::Ripple,      ModDest::DropletAmount,  0.35f },
        { ModSource::AmpEnvelope, ModDest::DropletAmount,  0.30f },
        { ModSource::ModWheel,    ModDest::DropletDensity, 0.45f },
    }));

    out.push_back (make (kStorms, "RIPTIDE", "Bass", { "Chaotic", "Dark", "Deep" }, Dry::No,
        "FM between two detuned Sharks, with the mod envelope on the FM amount "
        "so every note starts metallic and collapses into a clean low note.",
    {
        { pid::oscAWave,      wv (OscWave::Shark) },
        { pid::oscAShape,     0.50f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (2) },
        { pid::oscADetune,    0.14f },
        { pid::oscAStereo,    0.35f },
        { pid::oscALevel,     lvl (-3.0f) },
        { pid::oscAPhase,     startPhase (0.0f) },

        { pid::oscBWave,      wv (OscWave::Saw) },
        { pid::oscBOctave,    oct (0) },
        { pid::oscBSemitone,  semi (7) },
        { pid::oscBLevel,     lvl (-22.0f) },
        { pid::oscBInterMode, im (InteractionMode::FM) },
        { pid::oscBInterAmt,  0.40f },
        { pid::oscBPhase,     startPhase (0.0f) },

        { pid::subWave,       sw (SubWave::Square) },
        { pid::subLevel,      lvl (-7.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-24.0f) },
        { pid::noiseTone,     0.28f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (240.0f) },
        { pid::filtReso,      0.50f },
        { pid::filtDrive,     0.60f },
        { pid::filtKeyTrack,  0.90f },
        { pid::filtEnvAmt,    bip (0.75f) },
        { pid::filtPressure,  0.70f },

        { pid::fenvAttack,    att (0.001f) },
        { pid::fenvDecay,     dec (0.20f) },
        { pid::fenvSustain,   0.08f },
        { pid::fenvRelease,   rel (0.20f) },
        { pid::fenvVelocity,  0.80f },

        { pid::aenvAttack,    att (0.002f) },
        { pid::aenvDecay,     dec (0.70f) },
        { pid::aenvSustain,   0.62f },
        { pid::aenvRelease,   rel (0.18f) },
        { pid::aenvVelocity,  0.65f },

        { pid::macroDepth,    0.85f },
        { pid::macroPressure, 0.80f },
        { pid::macroCurrent,  0.55f },
        { pid::macroRipple,   0.45f },
        { pid::fluidX,        bip (0.75f) },
        { pid::fluidY,        bip (0.70f) },

        { pid::tideRate,      tideHz (0.8f) },
        { pid::tideDepth,     0.25f },
        { pid::currRate,      currHz (2.8f) },
        { pid::currAmount,    0.50f },
        { pid::currSmooth,    0.30f },
        { pid::rippleRate,    rippleHz (10.0f) },
        { pid::rippleDecay,   0.85f },
        { pid::rippleDepth,   0.50f },
        { pid::rippleCycles,  cycles (2.0f) },

        { pid::resoAmount,    0.20f },
        { pid::resoSize,      0.28f },
        { pid::resoDecay,     0.30f },
        { pid::resoDamping,   0.78f },
        { pid::resoScatter,   0.45f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.22f },
        { pid::scurWidth,     0.35f },
        { pid::dlyEnable,     on },
        { pid::dlySync,       on },
        { pid::dlySyncTime,   sd (SyncDivision::Sixteenth) },
        { pid::dlyFeedback,   0.30f },
        { pid::dlyDamping,    0.70f },
        { pid::dlyMix,        0.14f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.40f },
        { pid::verbDecay,     0.35f },
        { pid::verbLowCut,    vLowHz (450.0f) },
        { pid::verbMix,       0.14f },

        { pid::mastLow,       eqdb (2.5f) },
        { pid::mastMid,       eqdb (-2.5f) },
        { pid::mastDrive,     0.42f },
        { pid::mastCeiling,   ceildb (-1.0f) },
        { pid::voiceCount,    vox (1) },
        { pid::glideMode,     gmd (GlideMode::Legato) },
        { pid::glideTime,     gtime (0.04f) },
    },
    {
        { ModSource::ModEnvelope, ModDest::InteractionAmount, 0.70f },
        { ModSource::ModEnvelope, ModDest::FilterDrive,       0.30f },
        { ModSource::Velocity,    ModDest::InteractionAmount, 0.40f },
        { ModSource::Velocity,    ModDest::FilterCutoff,      0.45f },
        { ModSource::Ripple,      ModDest::PitchB,            0.18f },
        { ModSource::Current,     ModDest::InteractionAmount, 0.25f },
        { ModSource::ModWheel,    ModDest::InteractionAmount, 0.50f },
        { ModSource::KeyTrack,    ModDest::SubLevel,         -0.40f },
    }));

    out.push_back (make (kStorms, "THUNDERHEAD", "Drone", { "Dark", "Chaotic", "Cinematic" }, Dry::No,
        "A wall. Seven-voice unison two octaves down, heavy drive, a notch in "
        "the middle, and the longest reverb in the bank. For the two seconds "
        "before something terrible happens.",
    {
        { pid::oscAWave,      wv (OscWave::Saw) },
        { pid::oscAShape,     0.45f },
        { pid::oscAOctave,    oct (-2) },
        { pid::oscAUnison,    uni (7) },
        { pid::oscADetune,    0.42f },
        { pid::oscAStereo,    1.00f },
        { pid::oscALevel,     lvl (-7.0f) },

        { pid::oscBWave,      wv (OscWave::Shark) },
        { pid::oscBOctave,    oct (-2) },
        { pid::oscBFine,      cents (-22.0f) },
        { pid::oscBUnison,    uni (5) },
        { pid::oscBDetune,    0.38f },
        { pid::oscBStereo,    1.00f },
        { pid::oscBLevel,     lvl (-11.0f) },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subOctave,     subOct (-2) },
        { pid::subLevel,      lvl (-8.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-16.0f) },
        { pid::noiseTone,     0.18f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (380.0f) },
        { pid::filtReso,      0.38f },
        { pid::filtDrive,     0.55f },
        { pid::filtKeyTrack,  0.20f },
        { pid::filtEnvAmt,    bip (0.28f) },
        { pid::filtPressure,  0.90f },

        { pid::fenvAttack,    att (4.00f) },
        { pid::fenvDecay,     dec (10.00f) },
        { pid::fenvSustain,   0.70f },
        { pid::fenvRelease,   rel (8.00f) },

        { pid::aenvAttack,    att (3.00f) },
        { pid::aenvDecay,     dec (8.00f) },
        { pid::aenvSustain,   0.92f },
        { pid::aenvRelease,   rel (9.00f) },
        { pid::aenvVelocity,  0.20f },

        { pid::macroDepth,    0.95f },
        { pid::macroPressure, 0.90f },
        { pid::macroSpace,    0.90f },
        { pid::macroCurrent,  0.60f },
        { pid::macroWet,      0.50f },
        { pid::fluidX,        bip (0.55f) },
        { pid::fluidY,        bip (0.90f) },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.04f) },
        { pid::tideDepth,     0.60f },
        { pid::tideStereo,    0.60f },
        { pid::currRate,      currHz (0.45f) },
        { pid::currAmount,    0.60f },
        { pid::currSmooth,    0.60f },
        { pid::currDrift,     0.60f },
        { pid::driftRate,     driftHz (0.01f) },
        { pid::driftAmount,   0.70f },

        { pid::dropAmount,    0.25f },
        { pid::dropDensity,   0.35f },
        { pid::dropSize,      0.80f },
        { pid::dropTone,      0.20f },
        { pid::dropSplash,    0.60f },
        { pid::dropRandom,    0.85f },
        { pid::dropSpread,    0.95f },

        { pid::resoAmount,    0.34f },
        { pid::resoSize,      0.90f },
        { pid::resoDecay,     0.82f },
        { pid::resoDamping,   0.75f },
        { pid::resoScatter,   0.50f },
        { pid::resoMotion,    0.45f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.50f },
        { pid::scurRate,      scurHz (0.04f) },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.12f) },
        { pid::chorDepth,     0.55f },
        { pid::chorMix,       0.26f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (2.20f) },
        { pid::dlyFeedback,   0.55f },
        { pid::dlyDamping,    0.85f },
        { pid::dlyMix,        0.20f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.75f },
        { pid::diffSize,      0.80f },
        { pid::diffMix,       0.38f },
        { pid::verbEnable,    on },
        { pid::verbSize,      1.00f },
        { pid::verbDecay,     0.95f },
        { pid::verbPredelay,  pre (110.0f) },
        { pid::verbDamping,   0.68f },
        { pid::verbLowCut,    vLowHz (55.0f) },
        { pid::verbHighCut,   vHighHz (3000.0f) },
        { pid::verbMod,       0.45f },
        { pid::verbMix,       0.52f },

        { pid::mastLow,       eqdb (3.0f) },
        { pid::mastMid,       eqdb (-3.0f) },
        { pid::mastHigh,      eqdb (-5.0f) },
        { pid::mastDrive,     0.35f },
        { pid::mastCeiling,   ceildb (-1.5f) },
        { pid::voiceCount,    vox (4) },
    },
    {
        { ModSource::Tide,     ModDest::FilterCutoff,   0.40f },
        { ModSource::Tide,     ModDest::Amplitude,      0.20f },
        { ModSource::Drift,    ModDest::FineAll,        0.35f },
        { ModSource::Drift,    ModDest::FilterCutoff,   0.30f },
        { ModSource::Current,  ModDest::FilterDrive,    0.35f },
        { ModSource::Current,  ModDest::PanB,           0.45f },
        { ModSource::Current,  ModDest::NoiseTone,      0.30f },
        { ModSource::ModWheel, ModDest::FilterCutoff,   0.50f },
        { ModSource::Aftertouch, ModDest::FilterDrive,  0.30f },
    }));

    out.push_back (make (kStorms, "MAELSTROM", "Lead", { "Chaotic", "Bright", "Dark" }, Dry::No,
        "A lead that fights back. Ring modulation at a fifth, high resonance, "
        "and the Ripple modulator retriggering on every note so the pitch never "
        "settles immediately. Mod wheel takes it over the edge.",
    {
        { pid::oscAWave,      wv (OscWave::Shark) },
        { pid::oscAShape,     0.58f },
        { pid::oscAUnison,    uni (3) },
        { pid::oscADetune,    0.18f },
        { pid::oscAStereo,    0.60f },
        { pid::oscALevel,     lvl (-4.0f) },

        { pid::oscBWave,      wv (OscWave::Pulse) },
        { pid::oscBShape,     0.28f },
        { pid::oscBSemitone,  semi (7) },
        { pid::oscBLevel,     lvl (-16.0f) },
        { pid::oscBInterMode, im (InteractionMode::RingMod) },
        { pid::oscBInterAmt,  0.45f },

        { pid::subLevel,      lvl (-13.0f) },
        { pid::noiseType,     nz (NoiseType::White) },
        { pid::noiseLevel,    lvl (-28.0f) },
        { pid::noiseTone,     0.60f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (1500.0f) },
        { pid::filtReso,      0.62f },
        { pid::filtDrive,     0.48f },
        { pid::filtKeyTrack,  0.70f },
        { pid::filtEnvAmt,    bip (0.55f) },
        { pid::filtPressure,  0.45f },

        { pid::fenvAttack,    att (0.004f) },
        { pid::fenvDecay,     dec (0.40f) },
        { pid::fenvSustain,   0.30f },
        { pid::fenvRelease,   rel (0.40f) },
        { pid::fenvVelocity,  0.70f },

        { pid::aenvAttack,    att (0.006f) },
        { pid::aenvDecay,     dec (0.90f) },
        { pid::aenvSustain,   0.82f },
        { pid::aenvRelease,   rel (0.50f) },
        { pid::aenvVelocity,  0.60f },

        { pid::macroCurrent,  0.75f },
        { pid::macroRipple,   0.80f },
        { pid::macroDepth,    0.55f },
        { pid::macroGlow,     0.55f },
        { pid::macroSpace,    0.50f },
        { pid::fluidX,        bip (0.95f) },
        { pid::fluidY,        bip (0.30f) },
        { pid::fluidXAmount,  0.95f },

        { pid::tideShape,     ts (TideShape::Triangle) },
        { pid::tideRate,      tideHz (5.5f) },
        { pid::tideDepth,     0.25f },
        { pid::tideStereo,    0.50f },
        { pid::currRate,      currHz (5.0f) },
        { pid::currAmount,    0.75f },
        { pid::currSmooth,    0.20f },
        { pid::currStereo,    0.75f },
        { pid::rippleRate,    rippleHz (18.0f) },
        { pid::rippleDecay,   0.60f },
        { pid::rippleDepth,   0.55f },
        { pid::rippleCycles,  cycles (10.0f) },
        { pid::rippleSpread,  0.65f },
        { pid::ripplePolarity, on },

        { pid::dropAmount,    0.25f },
        { pid::dropMode,      dm (DropletMode::Note) },
        { pid::dropDensity,   0.50f },
        { pid::dropSize,      0.30f },
        { pid::dropTone,      0.65f },
        { pid::dropSplash,    0.75f },
        { pid::dropRandom,    0.85f },

        { pid::resoAmount,    0.30f },
        { pid::resoSize,      0.38f },
        { pid::resoDecay,     0.48f },
        { pid::resoDamping,   0.42f },
        { pid::resoScatter,   0.75f },
        { pid::resoMotion,    0.70f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.40f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (2.0f) },
        { pid::chorDepth,     0.30f },
        { pid::chorMix,       0.20f },
        { pid::dlyEnable,     on },
        { pid::dlySync,       on },
        { pid::dlySyncTime,   sd (SyncDivision::EighthT) },
        { pid::dlyFeedback,   0.58f },
        { pid::dlyMotion,     0.70f },
        { pid::dlySpread,     0.85f },
        { pid::dlyMix,        0.26f },
        { pid::diffEnable,    on },
        { pid::diffMix,       0.24f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.62f },
        { pid::verbDecay,     0.58f },
        { pid::verbMix,       0.28f },

        { pid::mastMid,       eqdb (-1.5f) },
        { pid::mastDrive,     0.34f },
        { pid::mastCeiling,   ceildb (-1.0f) },
        { pid::voiceCount,    vox (1) },
        { pid::glideMode,     gmd (GlideMode::Legato) },
        { pid::glideTime,     gtime (0.06f) },
        { pid::bendRange,     bend (12) },
    },
    {
        { ModSource::Ripple,      ModDest::PitchAll,          0.14f },
        { ModSource::Ripple,      ModDest::FilterCutoff,      0.45f },
        { ModSource::Ripple,      ModDest::InteractionAmount, 0.35f },
        { ModSource::Current,     ModDest::FilterCutoff,      0.50f },
        { ModSource::Current,     ModDest::ResonatorScatter,  0.45f },
        { ModSource::Tide,        ModDest::ShapeA,            0.30f },
        { ModSource::ModWheel,    ModDest::InteractionAmount, 0.55f },
        { ModSource::ModWheel,    ModDest::FilterResonance,   0.35f },
        { ModSource::Aftertouch,  ModDest::FilterCutoff,      0.40f },
        { ModSource::Velocity,    ModDest::FilterCutoff,      0.40f },
        { ModSource::ModEnvelope, ModDest::ShapeB,            0.35f },
    }));
}

} // namespace ripples::factory
