#include "Presets/PresetAuthoring.h"
#include "Presets/Banks.h"

/*
    RIPPLES — the CURRENTS bank.

    See Presets/PresetAuthoring.h for the unit helpers and the make() form, and
    docs/PRESET_GUIDE.md for what makes a preset in this bank good.
*/

namespace ripples::factory
{

//==============================================================================
//  CURRENTS — motion first. The Current, Drift and Tide modulators lead.
//==============================================================================
void addCurrentsBank (std::vector<Preset>& out)
{
    // --- DRY AQUATIC #11 ---------------------------------------------------
    out.push_back (make (kCurrents, "CRYSTAL CURRENT", "Arp", { "Glassy", "Bright", "Wet" }, Dry::Yes,
        "Built for fast arpeggios with no delay under them: the repeats come "
        "from the resonator and the per-note random pan, and Current keeps the "
        "timbre moving so a repeated pattern never sounds looped.",
    {
        RIPPLES_FX_BYPASSED,

        { pid::oscAWave,      wv (OscWave::Glass) },
        { pid::oscAShape,     0.66f },
        { pid::oscAUnison,    uni (2) },
        { pid::oscADetune,    0.08f },
        { pid::oscAStereo,    0.70f },
        { pid::oscALevel,     lvl (-3.0f) },
        { pid::oscAPhase,     startPhase (0.0f) },

        { pid::oscBWave,      wv (OscWave::Water) },
        { pid::oscBOctave,    oct (1) },
        { pid::oscBShape,     0.45f },
        { pid::oscBFine,      cents (6.0f) },
        { pid::oscBLevel,     lvl (-11.0f) },
        { pid::oscBStereo,    0.75f },

        { pid::subLevel,      lvl (-21.0f) },
        { pid::noiseType,     nz (NoiseType::Bubble) },
        { pid::noiseLevel,    lvl (-24.0f) },
        { pid::noiseTone,     0.75f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (1900.0f) },
        { pid::filtReso,      0.42f },
        { pid::filtDrive,     0.12f },
        { pid::filtKeyTrack,  0.75f },
        { pid::filtEnvAmt,    bip (0.55f) },
        { pid::filtPressure,  0.20f },

        { pid::fenvAttack,    att (0.001f) },
        { pid::fenvDecay,     dec (0.22f) },
        { pid::fenvSustain,   0.05f },
        { pid::fenvRelease,   rel (0.25f) },
        { pid::fenvVelocity,  0.70f },

        { pid::aenvAttack,    att (0.001f) },
        { pid::aenvDecay,     dec (0.60f) },
        { pid::aenvSustain,   0.05f },
        { pid::aenvRelease,   rel (0.50f) },
        { pid::aenvVelocity,  0.75f },

        { pid::macroCurrent,  0.75f },
        { pid::macroWet,      0.55f },
        { pid::macroGlow,     0.70f },
        { pid::macroRipple,   0.40f },
        { pid::macroDrops,    0.35f },
        { pid::fluidX,        bip (0.40f) },
        { pid::fluidY,        bip (-0.35f) },
        { pid::fluidXAmount,  0.70f },

        { pid::tideShape,     ts (TideShape::Triangle) },
        { pid::tideSync,      on },
        { pid::tideSyncRate,  sd (SyncDivision::TwoBars) },
        { pid::tideDepth,     0.50f },
        { pid::tideStereo,    0.60f },
        { pid::currRate,      currHz (2.4f) },
        { pid::currAmount,    0.65f },
        { pid::currSmooth,    0.40f },
        { pid::currDrift,     0.30f },
        { pid::currStereo,    0.90f },
        { pid::driftRate,     driftHz (0.06f) },
        { pid::driftAmount,   0.35f },
        { pid::rippleRate,    rippleHz (11.0f) },
        { pid::rippleDecay,   0.82f },
        { pid::rippleDepth,   0.38f },
        { pid::rippleCycles,  cycles (4.0f) },
        { pid::rippleSpread,  0.60f },

        { pid::dropAmount,    0.30f },
        { pid::dropMode,      dm (DropletMode::Note) },
        { pid::dropDensity,   0.30f },
        { pid::dropSize,      0.20f },
        { pid::dropTone,      0.85f },
        { pid::dropSplash,    0.40f },
        { pid::dropSpread,    0.90f },

        { pid::resoAmount,    0.55f },
        { pid::resoSize,      0.40f },
        { pid::resoDecay,     0.62f },
        { pid::resoDamping,   0.30f },
        { pid::resoScatter,   0.50f },
        { pid::resoMotion,    0.55f },

        { pid::mastHigh,      eqdb (2.0f) },
        { pid::mastDrive,     0.10f },
    },
    {
        { ModSource::Current,       ModDest::ShapeA,           0.50f },
        { ModSource::Current,       ModDest::FilterCutoff,     0.40f },
        { ModSource::Current,       ModDest::ResonatorScatter, 0.35f },
        { ModSource::Tide,          ModDest::FilterCutoff,     0.35f },
        { ModSource::Ripple,        ModDest::ResonatorSize,   -0.30f },
        { ModSource::RandomPerNote, ModDest::PanA,             0.55f },
        { ModSource::RandomPerNote, ModDest::ResonatorSize,    0.20f },
        { ModSource::Velocity,      ModDest::FilterCutoff,     0.40f },
        { ModSource::KeyTrack,      ModDest::ResonatorDecay,  -0.25f },
    }));

    out.push_back (make (kCurrents, "UNDERTOW", "Bass", { "Dark", "Deep", "Organic" }, Dry::No,
        "A bass that will not sit still. Current runs the cutoff at about two "
        "cycles a second and the drive with it, so the tone pulls away and back "
        "under a steady note.",
    {
        { pid::oscAWave,      wv (OscWave::Saw) },
        { pid::oscAShape,     0.48f },
        { pid::oscAOctave,    oct (-1) },
        { pid::oscAUnison,    uni (2) },
        { pid::oscADetune,    0.12f },
        { pid::oscAStereo,    0.30f },
        { pid::oscALevel,     lvl (-3.0f) },

        { pid::oscBWave,      wv (OscWave::Water) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBShape,     0.40f },
        { pid::oscBFine,      cents (-12.0f) },
        { pid::oscBLevel,     lvl (-9.0f) },

        { pid::subWave,       sw (SubWave::Sine) },
        { pid::subLevel,      lvl (-8.0f) },
        { pid::noiseType,     nz (NoiseType::Deep) },
        { pid::noiseLevel,    lvl (-27.0f) },
        { pid::noiseTone,     0.22f },

        { pid::filtMode,      fm (FilterMode::LP24) },
        { pid::filtCutoff,    hz (300.0f) },
        { pid::filtReso,      0.45f },
        { pid::filtDrive,     0.40f },
        { pid::filtKeyTrack,  0.85f },
        { pid::filtEnvAmt,    bip (0.50f) },
        { pid::filtPressure,  0.65f },

        { pid::fenvAttack,    att (0.002f) },
        { pid::fenvDecay,     dec (0.50f) },
        { pid::fenvSustain,   0.25f },
        { pid::fenvRelease,   rel (0.35f) },
        { pid::fenvVelocity,  0.65f },

        { pid::aenvAttack,    att (0.004f) },
        { pid::aenvDecay,     dec (1.00f) },
        { pid::aenvSustain,   0.75f },
        { pid::aenvRelease,   rel (0.30f) },
        { pid::aenvVelocity,  0.50f },

        { pid::macroDepth,    0.80f },
        { pid::macroCurrent,  0.80f },
        { pid::macroPressure, 0.65f },
        { pid::macroWet,      0.35f },
        { pid::fluidX,        bip (0.35f) },
        { pid::fluidY,        bip (0.60f) },

        { pid::tideRate,      tideHz (0.45f) },
        { pid::tideDepth,     0.20f },
        { pid::currRate,      currHz (2.0f) },
        { pid::currAmount,    0.70f },
        { pid::currSmooth,    0.45f },
        { pid::currDrift,     0.40f },
        { pid::currStereo,    0.40f },
        { pid::driftRate,     driftHz (0.04f) },
        { pid::driftAmount,   0.30f },

        { pid::resoAmount,    0.20f },
        { pid::resoSize,      0.34f },
        { pid::resoDecay,     0.35f },
        { pid::resoDamping,   0.75f },
        { pid::resoMotion,    0.40f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.20f },
        { pid::scurWidth,     0.35f },
        { pid::diffEnable,    on },
        { pid::diffAmount,    0.30f },
        { pid::diffMix,       0.16f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.45f },
        { pid::verbDecay,     0.40f },
        { pid::verbLowCut,    vLowHz (350.0f) },
        { pid::verbMix,       0.16f },

        { pid::mastLow,       eqdb (2.0f) },
        { pid::mastDrive,     0.26f },
        { pid::voiceCount,    vox (2) },
        { pid::glideMode,     gmd (GlideMode::Legato) },
        { pid::glideTime,     gtime (0.08f) },
    },
    {
        { ModSource::Current,     ModDest::FilterCutoff, 0.60f },
        { ModSource::Current,     ModDest::FilterDrive,  0.35f },
        { ModSource::Current,     ModDest::ShapeA,       0.30f },
        { ModSource::Drift,       ModDest::FilterCutoff, 0.25f },
        { ModSource::Velocity,    ModDest::FilterCutoff, 0.40f },
        { ModSource::ModEnvelope, ModDest::SubLevel,     0.25f },
        { ModSource::ModWheel,    ModDest::FilterResonance, 0.30f },
    }));

    out.push_back (make (kCurrents, "GULF STREAM", "Pad", { "Calm", "Dreamy", "Deep" }, Dry::No,
        "The slowest thing in the bank. Drift at one cycle every three minutes "
        "moves tuning, cutoff and stereo position together, so a held chord is "
        "never quite the same chord twice.",
    {
        { pid::oscAWave,      wv (OscWave::Water) },
        { pid::oscAShape,     0.48f },
        { pid::oscAUnison,    uni (6) },
        { pid::oscADetune,    0.28f },
        { pid::oscAStereo,    0.95f },
        { pid::oscALevel,     lvl (-5.0f) },

        { pid::oscBWave,      wv (OscWave::Sine) },
        { pid::oscBOctave,    oct (1) },
        { pid::oscBFine,      cents (3.0f) },
        { pid::oscBUnison,    uni (3) },
        { pid::oscBDetune,    0.20f },
        { pid::oscBStereo,    0.90f },
        { pid::oscBLevel,     lvl (-14.0f) },

        { pid::subLevel,      lvl (-17.0f) },
        { pid::noiseType,     nz (NoiseType::Surf) },
        { pid::noiseLevel,    lvl (-28.0f) },
        { pid::noiseTone,     0.45f },

        { pid::filtMode,      fm (FilterMode::LP12) },
        { pid::filtCutoff,    hz (1700.0f) },
        { pid::filtReso,      0.18f },
        { pid::filtKeyTrack,  0.40f },
        { pid::filtEnvAmt,    bip (0.28f) },
        { pid::filtPressure,  0.45f },

        { pid::fenvAttack,    att (3.00f) },
        { pid::fenvDecay,     dec (6.00f) },
        { pid::fenvSustain,   0.60f },
        { pid::fenvRelease,   rel (6.00f) },

        { pid::aenvAttack,    att (2.20f) },
        { pid::aenvDecay,     dec (5.00f) },
        { pid::aenvSustain,   0.88f },
        { pid::aenvRelease,   rel (6.00f) },
        { pid::aenvVelocity,  0.20f },

        { pid::macroCurrent,  0.60f },
        { pid::macroDepth,    0.55f },
        { pid::macroWet,      0.55f },
        { pid::macroSpace,    0.75f },
        { pid::macroGlow,     0.40f },
        { pid::fluidX,        bip (-0.50f) },
        { pid::fluidY,        bip (0.25f) },

        { pid::tideShape,     ts (TideShape::Flow) },
        { pid::tideRate,      tideHz (0.05f) },
        { pid::tideDepth,     0.45f },
        { pid::tideStereo,    0.85f },
        { pid::currRate,      currHz (0.10f) },
        { pid::currAmount,    0.55f },
        { pid::currSmooth,    0.92f },
        { pid::currDrift,     0.55f },
        { pid::currStereo,    0.90f },
        { pid::driftRate,     driftHz (0.005f) },
        { pid::driftAmount,   0.80f },
        { pid::driftStereo,   0.95f },

        { pid::resoAmount,    0.24f },
        { pid::resoSize,      0.75f },
        { pid::resoDecay,     0.66f },
        { pid::resoDamping,   0.55f },
        { pid::resoMotion,    0.45f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.50f },
        { pid::scurRate,      scurHz (0.025f) },
        { pid::scurWidth,     0.70f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (0.09f) },
        { pid::chorDepth,     0.55f },
        { pid::chorDelay,     chdel (26.0f) },
        { pid::chorMix,       0.34f },
        { pid::dlyEnable,     on },
        { pid::dlyTime,       dtime (1.40f) },
        { pid::dlyFeedback,   0.44f },
        { pid::dlyMotion,     0.55f },
        { pid::dlyDamping,    0.75f },
        { pid::dlyMix,        0.20f },
        { pid::diffEnable,    on },
        { pid::diffMix,       0.30f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.85f },
        { pid::verbDecay,     0.82f },
        { pid::verbMod,       0.50f },
        { pid::verbMix,       0.44f },
    },
    {
        { ModSource::Drift,   ModDest::FineAll,        0.30f },
        { ModSource::Drift,   ModDest::FilterCutoff,   0.35f },
        { ModSource::Drift,   ModDest::PanA,           0.40f },
        { ModSource::Drift,   ModDest::StereoWidth,    0.30f },
        { ModSource::Current, ModDest::OscMix,         0.35f },
        { ModSource::Current, ModDest::ResonatorSize,  0.25f },
        { ModSource::Tide,    ModDest::ShapeA,         0.35f },
        { ModSource::Tide,    ModDest::DelayMotion,    0.25f },
    }));

    out.push_back (make (kCurrents, "EDDY", "Arp", { "Chaotic", "Wet", "Bright" }, Dry::No,
        "A synced sixteenth-note tide against a free-running Current, so the "
        "pattern turns against itself. Ring-modulated highs for the spin.",
    {
        { pid::oscAWave,      wv (OscWave::Pulse) },
        { pid::oscAShape,     0.35f },
        { pid::oscAUnison,    uni (2) },
        { pid::oscADetune,    0.10f },
        { pid::oscAStereo,    0.65f },
        { pid::oscALevel,     lvl (-4.0f) },
        { pid::oscAPhase,     startPhase (0.0f) },

        { pid::oscBWave,      wv (OscWave::Glass) },
        { pid::oscBOctave,    oct (1) },
        { pid::oscBSemitone,  semi (7) },
        { pid::oscBLevel,     lvl (-13.0f) },
        { pid::oscBInterMode, im (InteractionMode::RingMod) },
        { pid::oscBInterAmt,  0.35f },

        { pid::subLevel,      lvl (-19.0f) },
        { pid::noiseType,     nz (NoiseType::Bubble) },
        { pid::noiseLevel,    lvl (-23.0f) },
        { pid::noiseTone,     0.68f },

        { pid::filtMode,      fm (FilterMode::Morph) },
        { pid::filtCutoff,    hz (2100.0f) },
        { pid::filtReso,      0.48f },
        { pid::filtDrive,     0.20f },
        { pid::filtKeyTrack,  0.65f },
        { pid::filtEnvAmt,    bip (0.50f) },
        { pid::filtMovement,  0.40f },

        { pid::fenvAttack,    att (0.001f) },
        { pid::fenvDecay,     dec (0.14f) },
        { pid::fenvSustain,   0.00f },
        { pid::fenvRelease,   rel (0.18f) },
        { pid::fenvVelocity,  0.75f },

        { pid::aenvAttack,    att (0.001f) },
        { pid::aenvDecay,     dec (0.35f) },
        { pid::aenvSustain,   0.00f },
        { pid::aenvRelease,   rel (0.28f) },
        { pid::aenvVelocity,  0.80f },

        { pid::macroCurrent,  0.85f },
        { pid::macroRipple,   0.55f },
        { pid::macroWet,      0.50f },
        { pid::macroGlow,     0.60f },
        { pid::fluidX,        bip (0.70f) },
        { pid::fluidY,        bip (-0.25f) },
        { pid::fluidXAmount,  0.85f },

        { pid::tideShape,     ts (TideShape::DoubleWave) },
        { pid::tideSync,      on },
        { pid::tideSyncRate,  sd (SyncDivision::Sixteenth) },
        { pid::tideDepth,     0.55f },
        { pid::tideStereo,    0.70f },
        { pid::currRate,      currHz (3.5f) },
        { pid::currAmount,    0.70f },
        { pid::currSmooth,    0.30f },
        { pid::currStereo,    0.90f },
        { pid::rippleRate,    rippleHz (14.0f) },
        { pid::rippleDecay,   0.85f },
        { pid::rippleDepth,   0.45f },
        { pid::rippleCycles,  cycles (2.5f) },

        { pid::dropAmount,    0.25f },
        { pid::dropMode,      dm (DropletMode::Note) },
        { pid::dropDensity,   0.35f },
        { pid::dropSize,      0.22f },
        { pid::dropTone,      0.82f },
        { pid::dropRandom,    0.75f },
        { pid::dropSpread,    0.90f },

        { pid::resoAmount,    0.38f },
        { pid::resoSize,      0.36f },
        { pid::resoDecay,     0.45f },
        { pid::resoDamping,   0.38f },
        { pid::resoScatter,   0.65f },
        { pid::resoMotion,    0.65f },

        { pid::scurEnable,    on },
        { pid::scurAmount,    0.45f },
        { pid::chorEnable,    on },
        { pid::chorRate,      chorHz (1.5f) },
        { pid::chorDepth,     0.35f },
        { pid::chorMix,       0.24f },
        { pid::dlyEnable,     on },
        { pid::dlySync,       on },
        { pid::dlySyncTime,   sd (SyncDivision::SixteenthD) },
        { pid::dlyFeedback,   0.52f },
        { pid::dlyMotion,     0.60f },
        { pid::dlySpread,     0.75f },
        { pid::dlyMix,        0.28f },
        { pid::verbEnable,    on },
        { pid::verbSize,      0.55f },
        { pid::verbDecay,     0.50f },
        { pid::verbMix,       0.26f },
        { pid::mastHigh,      eqdb (1.5f) },
    },
    {
        { ModSource::Tide,          ModDest::FilterMovement,    0.50f },
        { ModSource::Tide,          ModDest::ShapeA,            0.40f },
        { ModSource::Current,       ModDest::FilterCutoff,      0.55f },
        { ModSource::Current,       ModDest::InteractionAmount, 0.40f },
        { ModSource::Ripple,        ModDest::PitchB,            0.10f },
        { ModSource::RandomPerNote, ModDest::PanA,              0.50f },
        { ModSource::RandomPerNote, ModDest::ShapeA,            0.25f },
        { ModSource::Velocity,      ModDest::InteractionAmount, 0.30f },
    }));

    // --- DRY AQUATIC #12 ---------------------------------------------------
    out.push_back (make (kCurrents, "RIVER MOUTH", "Texture", { "Organic", "Calm", "Surface" }, Dry::Yes,
        "Where the fresh water meets the salt. Surf noise and a Water oscillator "
        "share a slow Morph filter, and the stereo image comes entirely from "
        "decorrelated Current and Drift — there is no width effect running.",
    {
        RIPPLES_FX_BYPASSED,

        { pid::oscAWave,      wv (OscWave::Water) },
        { pid::oscAShape,     0.58f },
        { pid::oscAUnison,    uni (5) },
        { pid::oscADetune,    0.24f },
        { pid::oscAStereo,    1.00f },
        { pid::oscAPan,       bip (-0.15f) },
        { pid::oscALevel,     lvl (-7.0f) },

        { pid::oscBWave,      wv (OscWave::Hollow) },
        { pid::oscBOctave,    oct (-1) },
        { pid::oscBFine,      cents (11.0f) },
        { pid::oscBUnison,    uni (3) },
        { pid::oscBDetune,    0.26f },
        { pid::oscBStereo,    1.00f },
        { pid::oscBPan,       bip (0.15f) },
        { pid::oscBLevel,     lvl (-10.0f) },

        { pid::subLevel,      lvl (-19.0f) },
        { pid::noiseType,     nz (NoiseType::Surf) },
        { pid::noiseLevel,    lvl (-13.0f) },
        { pid::noiseTone,     0.48f },

        { pid::filtMode,      fm (FilterMode::Morph) },
        { pid::filtCutoff,    hz (1300.0f) },
        { pid::filtReso,      0.30f },
        { pid::filtDrive,     0.14f },
        { pid::filtKeyTrack,  0.35f },
        { pid::filtEnvAmt,    bip (0.22f) },
        { pid::filtMovement,  0.25f },
        { pid::filtPressure,  0.40f },

        { pid::fenvAttack,    att (1.50f) },
        { pid::fenvDecay,     dec (4.00f) },
        { pid::fenvSustain,   0.55f },
        { pid::fenvRelease,   rel (4.00f) },

        { pid::aenvAttack,    att (1.20f) },
        { pid::aenvDecay,     dec (3.50f) },
        { pid::aenvSustain,   0.82f },
        { pid::aenvRelease,   rel (4.50f) },
        { pid::aenvVelocity,  0.25f },

        { pid::macroCurrent,  0.70f },
        { pid::macroWet,      0.60f },
        { pid::macroDepth,    0.45f },
        { pid::macroDrops,    0.35f },
        { pid::macroGlow,     0.40f },
        { pid::fluidX,        bip (0.15f) },
        { pid::fluidY,        bip (-0.15f) },

        { pid::tideShape,     ts (TideShape::Swell) },
        { pid::tideRate,      tideHz (0.14f) },
        { pid::tideDepth,     0.50f },
        { pid::tideStereo,    0.90f },
        { pid::currRate,      currHz (0.85f) },
        { pid::currAmount,    0.65f },
        { pid::currSmooth,    0.60f },
        { pid::currDrift,     0.50f },
        { pid::currStereo,    1.00f },
        { pid::driftRate,     driftHz (0.03f) },
        { pid::driftAmount,   0.55f },
        { pid::driftStereo,   1.00f },

        { pid::dropAmount,    0.34f },
        { pid::dropDensity,   0.45f },
        { pid::dropSize,      0.40f },
        { pid::dropTone,      0.58f },
        { pid::dropSplash,    0.50f },
        { pid::dropRandom,    0.80f },
        { pid::dropSpread,    1.00f },

        { pid::resoAmount,    0.34f },
        { pid::resoSize,      0.62f },
        { pid::resoDecay,     0.52f },
        { pid::resoDamping,   0.50f },
        { pid::resoScatter,   0.55f },
        { pid::resoMotion,    0.60f },

        { pid::mastLow,       eqdb (-1.0f) },
        { pid::mastDrive,     0.08f },
    },
    {
        { ModSource::Current,     ModDest::FilterMovement, 0.55f },
        { ModSource::Current,     ModDest::PanA,           0.55f },
        { ModSource::Current,     ModDest::NoiseTone,      0.40f },
        { ModSource::Drift,       ModDest::PanB,          -0.50f },
        { ModSource::Drift,       ModDest::FilterCutoff,   0.30f },
        { ModSource::Tide,        ModDest::NoiseLevel,     0.40f },
        { ModSource::Tide,        ModDest::OscMix,         0.30f },
        { ModSource::AmpEnvelope, ModDest::DropletAmount,  0.35f },
        { ModSource::ModWheel,    ModDest::FilterMovement, 0.40f },
    }));
}

} // namespace ripples::factory
